import { useLoad, words } from './useLoad'
import { useCallback, useState } from 'react'
import { Link, useSearchParams } from 'react-router'
import { api, apiFailure } from '../../services/api'
import { marketplace, downloadCv, type Candidate, type SearchPage } from './api'
import { Workspace, LoadState, Feedback, Empty, Field } from './shared'
const setup = () => Promise.all([marketplace.jobs(), marketplace.skills()])
export function CandidateSearchPage() {
  const state = useLoad(setup)
  const [params, setParams] = useSearchParams(), jobId = params.get('job') ?? ''
  const [filters, setFilters] = useState({ candidateType: '', location: '', skillId: '', availability: 'AVAILABLE' })
  const [query, setQuery] = useState(filters), [page, setPage] = useState(0), [tab, setTab] = useState<'search' | 'shortlist'>('search')
  const searchLoader = useCallback(() => api.get<SearchPage>('/candidates', { params: { ...Object.fromEntries(Object.entries(query).filter(([, v]) => v)), page } }).then(r => r.data), [query, page])
  const shortlistLoader = useCallback(() => jobId ? api.get<Candidate[]>(`/jobs/${jobId}/shortlist`).then(r => r.data) : Promise.resolve([]), [jobId])
  const search = useLoad(searchLoader), shortlist = useLoad(shortlistLoader)
  const [busy, setBusy] = useState<number | null>(null), [error, setError] = useState(''), [success, setSuccess] = useState('')
  const job = state.data?.[0].find(j => String(j.id) === jobId)
  async function toggle(c: Candidate, remove: boolean) {
    setBusy(c.id); setError(''); setSuccess('')
    try {
      if (remove) await api.delete(`/jobs/${jobId}/shortlist/${c.id}`)
      else await api.post(`/jobs/${jobId}/shortlist/${c.id}`)
      shortlist.setData(remove ? (shortlist.data ?? []).filter(s => s.id !== c.id) : [...(shortlist.data ?? []), c])
      setSuccess(remove ? `${c.fullName} removed from the shortlist.` : `${c.fullName} shortlisted for ${job?.title}.`)
    } catch (e) { setError(apiFailure(e).message) } finally { setBusy(null) }
  }
  async function hire(c: Candidate) {
    setBusy(c.id); setError(''); setSuccess('')
    try { await api.post('/placements', { jobId: Number(jobId), candidateId: c.id }); setSuccess(`Placement active for ${c.fullName}. View Placements for coverage and replacement options.`) } catch (e) { setError(apiFailure(e).message) } finally { setBusy(null) }
  }
  const activeState = tab === 'search' ? search : shortlist
  const cards = tab === 'search' ? search.data?.content : shortlist.data
  return <Workspace title="Discover your next hire" subtitle="Explore candidate skills and experience. Readiness labels only reflect released results; verification is a platform review."><LoadState {...state} />{!state.loading && !state.error && state.data && <>
    <section className="surface mb-6"><label className="field-label" htmlFor="job">Shortlist for an opening</label><select id="job" disabled={busy !== null} className="form-input" value={jobId} onChange={e => { setParams(e.target.value ? { job: e.target.value } : {}); setError(''); setSuccess('') }}><option value="">Choose one of your jobs</option>{state.data[0].map(j => <option key={j.id} value={j.id}>{j.title} · {words(j.status)}</option>)}</select>{!state.data[0].length && <p className="mt-4 text-sm"><Link className="text-indigo-700 underline" to="/employer/jobs">Create a job</Link> to start a shortlist.</p>}{job && <p className="mt-3 text-sm text-slate-500">{job.candidateType} · {job.requiredSkillName ?? 'Any skill'} · {job.location}{job.status === 'CLOSED' && ' · Closed: review or remove saved candidates.'}</p>}</section>
    <div className="mb-6 flex gap-2"><button className={tab === 'search' ? 'button-primary' : 'button-secondary'} onClick={() => setTab('search')}>Search talent</button><button className={tab === 'shortlist' ? 'button-primary' : 'button-secondary'} disabled={!job} onClick={() => setTab('shortlist')}>Shortlist{!shortlist.loading && shortlist.data ? ` (${shortlist.data.length})` : ''}</button></div>
    {tab === 'search' && <form className="surface mb-6" onSubmit={e => { e.preventDefault(); setQuery({ ...filters }); setPage(0) }}><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><label className="field-label" htmlFor="searchTrack">Track</label><select className="form-input" id="searchTrack" value={filters.candidateType} onChange={e => setFilters({ ...filters, candidateType: e.target.value })}><option value="">All tracks</option><option>TECH</option><option>TRADE</option></select></div><Field name="searchLocation" label="Location" value={filters.location} onChange={v => setFilters({ ...filters, location: v })} /><div><label className="field-label" htmlFor="searchSkill">Skill</label><select id="searchSkill" className="form-input" value={filters.skillId} onChange={e => setFilters({ ...filters, skillId: e.target.value })}><option value="">All skills</option>{state.data[1].map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div><label className="field-label" htmlFor="searchAvailability">Availability</label><select id="searchAvailability" className="form-input" value={filters.availability} onChange={e => setFilters({ ...filters, availability: e.target.value })}><option value="">Any availability</option><option value="AVAILABLE">Available</option><option value="UNAVAILABLE">Unavailable</option></select></div></div><button className="button-primary mt-5" disabled={search.loading}>Apply filters</button></form>}
    <Feedback error={error} success={success} /><LoadState {...activeState} />{shortlist.error && tab === 'search' && <LoadState {...shortlist} />}
    {!activeState.loading && !activeState.error && <>{tab === 'search' && <p className="mb-5 text-sm text-slate-500">{search.data?.totalElements ?? 0} candidates found</p>}{!cards?.length && <Empty title={tab === 'search' ? 'No candidates match these filters' : 'Your shortlist is ready to build'}>{tab === 'search' ? 'Try another location, skill or availability.' : 'Use Search talent to save suitable candidates for this opening.'}</Empty>}
      <div className="grid gap-5 md:grid-cols-2">{cards?.map(c => {
        const saved = shortlist.data?.some(s => s.id === c.id)
        const matches = job?.candidateType === c.candidateType && (!job.requiredSkillId || c.skills.some(s => s.id === job.requiredSkillId)) && c.availability === 'AVAILABLE'
        return <article className="surface flex flex-col" key={c.id}><div className="flex items-start gap-3"><span aria-hidden="true" className="grid size-12 shrink-0 place-items-center rounded-xl bg-indigo-50 text-xl font-bold text-indigo-700">{c.fullName.slice(0, 1)}</span><div className="min-w-0"><h2 className="break-words text-xl font-bold">{c.fullName}</h2><p className="mt-1 break-words text-sm text-slate-500">{c.candidateType} · {c.location || 'Location not provided'}</p></div></div><div className="my-4 flex flex-wrap gap-2"><span className={`badge ${c.availability === 'AVAILABLE' ? 'bg-emerald-50 text-emerald-800' : ''}`}>{words(c.availability)}</span><span className="badge">{c.verificationStatus === 'VERIFIED' ? 'Platform verified' : `Verification: ${words(c.verificationStatus)}`}</span></div><p className="line-clamp-3 break-words text-sm leading-relaxed text-slate-600">{c.experienceSummary || c.bio || 'This candidate is building their career profile.'}</p><div className="my-4 flex flex-wrap gap-2">{c.skills.length ? c.skills.map(s => <span className="badge" key={s.id}>{s.name}</span>) : <span className="text-sm text-slate-500">No skills listed</span>}</div><p className="mb-4 text-sm text-slate-500">{c.releasedResults.length ? c.releasedResults.map(r => `${words(r.recommendation)} · Score ${r.score}`).join(' / ') : 'Readiness: not yet assessed'}</p><div className="mt-auto flex flex-wrap gap-2">{c.portfolioUrl && <a className="button-secondary" href={c.portfolioUrl} target="_blank" rel="noreferrer">Portfolio ↗</a>}{c.hasCv && <button className="button-secondary" onClick={() => { setError(''); void downloadCv(`/candidates/${c.id}/cv`).catch(e => setError(apiFailure(e).message)) }}>Download CV</button>}<button className="button-primary" disabled={busy !== null || !job || shortlist.loading || Boolean(shortlist.error) || (!saved && (job.status !== 'ACTIVE' || !matches))} onClick={() => void toggle(c, Boolean(saved))}>{busy === c.id ? 'Updating…' : saved ? 'Remove from shortlist' : 'Shortlist candidate'}</button>{saved && job?.status === 'ACTIVE' && <button className="button-secondary" disabled={busy !== null || !job.requiredSkillId} onClick={() => { if (window.confirm(`Activate a placement for ${c.fullName}?`)) void hire(c) }}>Hire candidate</button>}</div>{saved && !job?.requiredSkillId && <p className="mt-3 text-xs text-slate-500">Set a required skill on this job before hiring.</p>}{!saved && job && !matches && <p className="mt-3 text-xs text-slate-500">Shortlisting requires availability and a matching track and skill.</p>}</article>
      })}</div>{tab === 'search' && (search.data?.totalPages ?? 0) > 1 && <div className="mt-6 flex items-center justify-center gap-4"><button className="button-secondary" disabled={page === 0} onClick={() => setPage(n => n - 1)}>Previous</button><span className="text-sm">{page + 1} / {search.data?.totalPages}</span><button className="button-secondary" disabled={page + 1 >= (search.data?.totalPages ?? 0)} onClick={() => setPage(n => n + 1)}>Next</button></div>}</>}
  </>}</Workspace>
}
