import { ActivitySummary } from './ActivitySummary'
import { ReadinessCard } from '../trade/ReadinessCard'
import { CareerActivity } from '../assessment/CareerActivity'
import { useLoad, words } from './useLoad'
import { Link } from 'react-router'
import { marketplace } from './api'
import { Workspace, LoadState, Stat, Empty } from './shared'
export function CandidateDashboard() {
  const state = useLoad(marketplace.profile), p = state.data
  const checks = p ? [Boolean(p.location), Boolean(p.experienceSummary), p.skills.length > 0, p.candidateType === 'TECH' ? Boolean(p.cvOriginalName) : Boolean(p.primaryTradeCategory)] : []
  const complete = checks.filter(Boolean).length
  return <Workspace title={p ? `Welcome, ${p.fullName}` : 'Your career, in focus'} subtitle="Build a clear profile, share your skills and keep your availability up to date."><LoadState {...state} />{!state.loading && !state.error && p && <>
    <section className="mb-6 grid gap-6 rounded-2xl bg-slate-900 p-6 text-white sm:p-8 md:grid-cols-[1.5fr_1fr]"><div><span className="rounded-full bg-white/10 px-3 py-1 text-xs font-semibold">{p.candidateType === 'TECH' ? 'TECH · Professional careers' : 'TRADE · দক্ষ কর্মী'}</span><h2 className="mt-5 text-2xl font-bold">{complete === 4 ? 'Your core profile is complete' : 'Let your next opportunity find you'}</h2><p className="mt-3 leading-relaxed text-slate-300">{p.candidateType === 'TRADE' ? 'আপনার দক্ষতা যোগ করুন এবং কাজের প্রস্তুতি জানান। Add your trade and experience so employers can find you.' : 'A location, experience summary, skills and CV help employers understand what you bring.'}</p><Link className="button-primary mt-5" to="/candidate/profile">{complete === 4 ? 'Manage profile' : 'Complete my profile'} →</Link></div><div className="rounded-xl bg-white/5 p-5"><div className="flex justify-between text-sm"><span>Core profile</span><strong>{complete}/4</strong></div><progress aria-label="Core profile completion" max={4} value={complete} className="my-4 h-2 w-full accent-emerald-400" /><ul className="space-y-2 text-sm text-slate-300">{['Location', 'Experience', 'Skills', p.candidateType === 'TECH' ? 'CV uploaded' : 'Trade category'].map((v, i) => <li key={v}>{checks[i] ? '✓' : '○'} {v}</li>)}</ul><p className="mt-4 text-xs text-slate-400">Profile completion is separate from verified readiness.</p></div></section>
    <div className="mb-6 grid gap-4 sm:grid-cols-3"><Stat label="Skills on your profile" value={p.skills.length} /><Stat label="Availability" value={words(p.availability)} /><Stat label="Released assessments" value={p.releasedResults.length} /></div>
    {p.candidateType === 'TRADE' && <><Link className="button-primary mb-6" to="/candidate/onboarding">বাংলায় শুরু করুন · Voice-assisted onboarding →</Link><ReadinessCard /></>}<CareerActivity /><ActivitySummary />
    <div className="grid gap-6 md:grid-cols-2"><section className="surface"><h2 className="text-xl font-bold">Your expertise</h2><p className="mt-2 text-sm text-slate-500">{p.primaryTradeCategory || p.location || 'Add your location to help employers find you.'}</p><div className="my-5 flex flex-wrap gap-2">{p.skills.map(s => <span className="badge" key={s.id}>{s.name}</span>)}</div>{!p.skills.length && <p className="my-5 text-sm text-slate-500">Add your first skill to appear in skill searches.</p>}<Link className="font-semibold text-indigo-700" to="/candidate/profile">Edit skills and availability →</Link></section><section className="surface"><h2 className="text-xl font-bold">Platform review</h2><p className="mt-4"><span className="badge">{words(p.verificationStatus)}</span></p><p className="mt-4 text-sm leading-relaxed text-slate-500">Verification is a manual platform review. An active account alone does not mean your skills or identity have been verified.</p>{p.releasedResults.length > 0 && <ul className="mt-4 space-y-2">{p.releasedResults.map((r, i) => <li key={i} className="text-sm font-semibold">{words(r.recommendation)} · Score {r.score}</li>)}</ul>}</section></div>
  </>}</Workspace>
}
const employerLoad = () => Promise.all([marketplace.company(), marketplace.jobs()])
export function EmployerDashboard() {
  const state = useLoad(employerLoad), company = state.data?.[0], jobs = state.data?.[1] ?? []
  return <Workspace title={company ? `Welcome, ${company.companyName}` : 'Your hiring, in focus'} subtitle="A clear view of your openings and the candidates you are considering."><LoadState {...state} />{!state.loading && !state.error && company && <>
    <section className="mb-6 rounded-2xl bg-slate-900 p-6 text-white sm:p-8"><p className="text-xs font-semibold uppercase tracking-widest text-indigo-200">Build with confidence</p><h2 className="mt-4 text-2xl font-bold">Good teams start with the right skills.</h2><p className="mt-3 max-w-2xl leading-relaxed text-slate-300">Create a focused opening, explore candidate profiles and bring your strongest matches into a shortlist.</p><div className="mt-6 flex flex-wrap gap-3"><Link className="button-primary" to="/employer/jobs">Manage openings →</Link><Link className="rounded-xl border border-slate-600 px-5 py-3 text-sm font-semibold" to="/employer/candidates">Find talent</Link></div></section>
    <div className="mb-6 grid gap-4 sm:grid-cols-3"><Stat label="Active jobs" value={jobs.filter(j => j.status === 'ACTIVE').length} /><Stat label="Shortlist entries" value={jobs.reduce((n, j) => n + j.shortlistCount, 0)} /><Stat label="Closed jobs" value={jobs.filter(j => j.status === 'CLOSED').length} /></div>
    <ActivitySummary /><div className="grid items-start gap-6 md:grid-cols-[1.5fr_1fr]"><section className="surface"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-bold">Recent openings</h2><Link to="/employer/jobs" className="text-sm font-semibold text-indigo-700">View all →</Link></div>{!jobs.length ? <Empty title="Make your first opening">Your jobs and shortlist activity will appear here once you create a role.</Empty> : <ul className="divide-y divide-slate-100">{jobs.slice(0, 5).map(j => <li className="py-4" key={j.id}><Link className="break-words font-bold text-indigo-700" to={`/employer/candidates?job=${j.id}`}>{j.title} →</Link><p className="mt-2 text-sm text-slate-500">{j.location} · {words(j.status)} · {j.shortlistCount} shortlisted</p><p className="mt-1 text-xs text-slate-500">Created {new Date(j.createdAt).toLocaleDateString()}</p></li>)}</ul>}</section><section className="surface"><h2 className="text-xl font-bold">Your company</h2><p className="mt-4 break-words font-semibold">{company.companyName}</p><p className="mt-2 text-sm text-slate-500">{company.industry || 'Add your industry'}</p><p className="mt-4 line-clamp-4 break-words text-sm leading-relaxed text-slate-600">{company.description || 'Introduce your company and give your hiring workspace a clear identity.'}</p><Link className="mt-5 inline-block font-semibold text-indigo-700" to="/employer/profile">Edit company profile →</Link></section></div>
  </>}</Workspace>
}
