import { payments } from '../payment/api'
import { useLoad, words } from './useLoad'
import { useState, type FormEvent } from 'react'
import { Link, useNavigate } from 'react-router'
import { api, apiFailure } from '../../services/api'
import { marketplace, type Job } from './api'
import { Workspace, LoadState, Field, Feedback, Empty } from './shared'
const load = () => Promise.all([marketplace.jobs(), marketplace.skills()])
const blank = { title: '', description: '', location: '', candidateType: 'TECH' as 'TECH' | 'TRADE', requiredSkillId: '', publicExpectations: '', privateExpectations: '', expectedExperienceMonths: '0' }
export function JobsPage() {
  const navigate = useNavigate()
  const state = useLoad(load)
  const [draft, setDraft] = useState(blank), [editing, setEditing] = useState<number | null>(null), [showForm, setShowForm] = useState(false)
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [success, setSuccess] = useState(''), [closing, setClosing] = useState<number | null>(null)
  const [fields, setFields] = useState<Record<string, string>>({})
  const hasApplicants = !!state.data?.[0].find(j => j.id === editing)?.applicationCount
  async function save(e: FormEvent) {
    e.preventDefault(); setBusy(true); setError(''); setSuccess(''); setFields({})
    const body = { ...draft, expectedExperienceMonths: Number(draft.expectedExperienceMonths), requiredSkillId: draft.requiredSkillId ? Number(draft.requiredSkillId) : null }
    try {
      const result = editing ? await api.put<Job>(`/jobs/${editing}`, body) : await api.post<Job>('/jobs', body)
      if (state.data) state.setData([[result.data, ...state.data[0].filter(j => j.id !== result.data.id)], state.data[1]])
      setShowForm(false); setDraft(blank); setEditing(null); setSuccess(editing ? 'Job updated.' : 'Job created. Complete payment to publish.')
    } catch (e) { const failure = apiFailure(e); setError(failure.message); setFields(failure.fieldErrors ?? {}) } finally { setBusy(false) }
  }
  async function pay(id: number) {
    setBusy(true); setError('')
    try { const payment = await payments.job(id); navigate(`/employer/payments/${payment.id}`) }
    catch (e) { setError(apiFailure(e).message) } finally { setBusy(false) }
  }
  async function close(id: number) {
    setBusy(true); setError(''); setSuccess('')
    try { const result = await api.post<Job>(`/jobs/${id}/close`); if (state.data) state.setData([state.data[0].map(j => j.id === id ? result.data : j), state.data[1]]); setClosing(null); setSuccess('Job closed. Your shortlist is still available.') }
    catch (e) { setError(apiFailure(e).message) } finally { setBusy(false) }
  }
  return <Workspace title="Build your next great team" subtitle="Manage openings and review candidates who apply to your jobs."><LoadState {...state} />{!state.loading && !state.error && state.data && <><Feedback error={error} success={success} />
    {!showForm && <button className="button-primary mb-6" onClick={() => { setEditing(null); setDraft(blank); setShowForm(true); setFields({}); setError('') }}>+ Create a job</button>}
    {showForm && <form className="surface mb-8" onSubmit={save}><h2 className="mb-6 text-xl font-bold">{editing ? 'Edit job' : 'Create an opening'}</h2><fieldset disabled={busy} className="space-y-5"><Field name="title" label="Job title" value={draft.title} required maxLength={200} error={fields.title} onChange={v => setDraft({ ...draft, title: v })} /><Field name="description" label="Responsibilities and requirements" value={draft.description} required maxLength={5000} multiline error={fields.description} onChange={v => setDraft({ ...draft, description: v })} /><Field name="publicExpectations" label="Candidate expectations · Visible to applicants" value={draft.publicExpectations} multiline maxLength={5000} error={fields.publicExpectations} onChange={v => setDraft({ ...draft, publicExpectations: v })} /><Field name="privateExpectations" label="Internal expectations · Not shown to applicants (optional)" value={draft.privateExpectations} multiline maxLength={5000} error={fields.privateExpectations} onChange={v => setDraft({ ...draft, privateExpectations: v })} /><label className="block"><span className="field-label">Expected experience (months)</span><input name="expectedExperienceMonths" type="number" min={0} step={1} required className="form-input" value={draft.expectedExperienceMonths} onChange={e => setDraft({ ...draft, expectedExperienceMonths: e.target.value })} /><span className="mt-1 block text-sm text-slate-500">0 welcomes fresh graduates and first-time workers.</span>{fields.expectedExperienceMonths && <span className="text-sm text-rose-700">{fields.expectedExperienceMonths}</span>}</label><div className="grid gap-5 sm:grid-cols-2"><Field name="location" label="Work location" value={draft.location} required error={fields.location} onChange={v => setDraft({ ...draft, location: v })} /><div><label className="field-label" htmlFor="track">Candidate track</label><select id="track" disabled={hasApplicants} className="form-input" value={draft.candidateType} onChange={e => setDraft({ ...draft, candidateType: e.target.value as 'TECH' | 'TRADE' })}><option>TECH</option><option>TRADE</option></select></div></div><div><label className="field-label" htmlFor="requiredSkill">Required skill</label><select id="requiredSkill" disabled={hasApplicants} className="form-input" value={draft.requiredSkillId} onChange={e => setDraft({ ...draft, requiredSkillId: e.target.value })}><option value="">Any skill</option>{state.data[1].map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select>{hasApplicants && <p className="mt-2 text-sm text-slate-500">Track and required skill are locked because this job has applications.</p>}</div><div className="flex flex-wrap gap-3"><button disabled={busy} className="button-primary">{busy ? 'Saving…' : editing ? 'Save changes' : 'Create job draft'}</button><button type="button" className="button-secondary" onClick={() => { setShowForm(false); setError('') }}>Cancel</button></div></fieldset></form>}
    {!state.data[0].length && <Empty title="Your first hire starts here">Create an opening with a clear role, location and required skill.</Empty>}
    <div className="grid gap-5 md:grid-cols-2">{state.data[0].map(j => <article className="surface flex flex-col" key={j.id}><div className="flex flex-wrap items-center justify-between gap-3"><span className="eyebrow">{j.candidateType}</span><span className={`badge ${j.status === 'ACTIVE' ? 'bg-emerald-50 text-emerald-800' : ''}`}>{j.status === 'DRAFT' ? 'Pending payment' : words(j.status)}</span></div><h2 className="mt-4 break-words text-xl font-bold">{j.title}</h2><p className="mt-2 text-sm text-slate-500">{j.location} · {j.requiredSkillName ?? 'Any skill'}</p><p className="mt-4 line-clamp-3 whitespace-pre-line break-words text-sm leading-relaxed text-slate-600">{j.description}</p><p className="my-5 text-sm font-semibold">{j.applicationCount} applications · {j.shortlistCount} shortlisted</p><div className="mt-auto flex flex-wrap gap-2"><Link to={`/employer/jobs/${j.id}/applications`} className="button-primary">View applicants</Link>{j.status === 'DRAFT' && <button disabled={busy} className="button-primary" onClick={() => void pay(j.id)}>Complete Payment</button>}{j.status !== 'CLOSED' && <><button disabled={busy} className="button-secondary" onClick={() => { setEditing(j.id); setDraft({ title: j.title, description: j.description, location: j.location, candidateType: j.candidateType, requiredSkillId: j.requiredSkillId?.toString() ?? '', publicExpectations: j.publicExpectations ?? '', privateExpectations: j.privateExpectations ?? '', expectedExperienceMonths: String(j.expectedExperienceMonths) }); setShowForm(true); setFields({}); setError(''); window.scrollTo({ top: 0, behavior: 'smooth' }) }}>Edit</button><button disabled={busy} className="button-secondary" onClick={() => setClosing(j.id)}>Close job</button></>}</div>{closing === j.id && <div className="mt-4 rounded-xl bg-amber-50 p-4"><p className="text-sm">Close this opening? It will stop accepting new shortlist entries and cannot be reopened.</p><div className="mt-3 flex gap-3"><button className="button-primary" disabled={busy} onClick={() => void close(j.id)}>Confirm close</button><button className="button-secondary" disabled={busy} onClick={() => setClosing(null)}>Keep open</button></div></div>}</article>)}</div></>}
  </Workspace>
}
