import { useTradeText } from '../trade/useTradeText'
import { useCallback, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router'
import { assessmentApi as service, type Attempt, type Option, type Result } from './api'
import { Workspace, LoadState, Feedback, Empty, Stat } from '../marketplace/shared'
import { useLoad, words } from '../marketplace/useLoad'
import { apiFailure } from '../../services/api'
const load = () => Promise.all([service.list(), service.mine()])
export function ResultSummary({ result }: { result: Result }) {
  const tr = useTradeText()

  return <section className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6"><p className="eyebrow">{tr("Released result")}</p><div className="mt-4 flex flex-wrap items-center gap-4"><strong className="text-4xl">{result.score}<span className="text-lg font-normal text-slate-500"> / 100</span></strong><span className="badge">{tr(words(result.recommendation))}</span></div><p className="mt-4 whitespace-pre-wrap break-words text-slate-700">{result.feedback}</p><Link className="mt-5 inline-block font-semibold text-indigo-700" to="/candidate/bookings">{tr("Discuss your next steps →")}</Link></section>
}
export function AssessmentsPage() {
  const tr = useTradeText()

  const state = useLoad(load), navigate = useNavigate(), [busy, setBusy] = useState<number | null>(null), [error, setError] = useState('')
  async function start(id: number) { setBusy(id); setError(''); try { const a = await service.start(id); navigate(`/candidate/assessments/${a.id}`) } catch (e) { setError(apiFailure(e).message) } finally { setBusy(null) } }
  const assessments = state.data?.[0] ?? [], attempts = state.data?.[1] ?? []
  return <Workspace title={tr("Show what you know")} subtitle={tr("Choose an assessment for your track. Save your progress, submit your answers and receive personal evaluator feedback.")}><LoadState {...state} /><Feedback error={error} />{!state.loading && !state.error && <>
    <div className="mb-6 grid gap-4 sm:grid-cols-3"><Stat label={tr("In progress")} value={attempts.filter(a => a.status === 'IN_PROGRESS').length} /><Stat label={tr("Awaiting review")} value={attempts.filter(a => a.status === 'SUBMITTED').length} /><Stat label={tr("Results released")} value={attempts.filter(a => a.result).length} /></div>
    {!assessments.length && <Empty title={tr("No assessments available yet")}>{tr("Your track’s assessments will appear here when published.")}</Empty>}
    <div className="grid gap-6 md:grid-cols-2">{assessments.map(a => { const attempt = attempts.find(t => t.assessment.id === a.id); return <section className="surface" key={a.id}><span className="badge">{tr(a.candidateType)} · {attempt ? tr(words(attempt.status)) : tr("Ready to start")}</span><h2 className="mt-5 text-xl font-bold">{a.title}</h2><p className="my-4 text-sm leading-relaxed text-slate-500">{a.questions.length}{' '}{tr("questions · Untimed ·")}{' '}{a.candidateType === 'TECH' ? 'Automatic scoring + evaluator review' : tr("পর্যালোচনা · Manual evaluator review")}</p><p className="mb-5 text-sm text-slate-600">{a.candidateType === 'TECH' ? `Reference passing score: ${a.passingScore ?? 70}/100. Your evaluator makes the final recommendation.` : tr("Your responses guide a practical skills conversation with an evaluator.")}</p><button className="button-primary" disabled={busy !== null} onClick={() => void start(a.id)}>{busy === a.id ? tr("Opening…") : !attempt ? tr("Start assessment →") : attempt.status === 'IN_PROGRESS' ? tr("Continue assessment →") : attempt.result ? tr("View result →") : tr("View submission →")}</button></section> })}</div>
    {attempts.filter(t => !assessments.some(a => a.id === t.assessment.id)).map(t => <Link className="surface mt-4 block" key={t.id} to={`/candidate/assessments/${t.id}`}>{t.assessment.title} · {tr(words(t.status))} →</Link>)}
  </>}</Workspace>
}
export function AttemptPage() {
  const tr = useTradeText()

  const { id } = useParams(), loader = useCallback(() => service.attempt(Number(id)), [id]), state = useLoad(loader)
  return <Workspace title={tr("Your assessment")} subtitle={tr("Take your time. Save answers before leaving; submitted answers are final.")}><LoadState {...state} />{state.data && <AttemptEditor key={state.data.id} initial={state.data} />}</Workspace>
}
function AttemptEditor({ initial }: { initial: Attempt }) {
  const tr = useTradeText()

  const [attempt, setAttempt] = useState(initial), [answers, setAnswers] = useState(initial.answers), [index, setIndex] = useState(0), [busy, setBusy] = useState(false), [confirm, setConfirm] = useState(false), [error, setError] = useState(''), [success, setSuccess] = useState('')
  const questions = attempt.assessment.questions, q = questions[index], complete = Object.keys(answers).length, editable = attempt.status === 'IN_PROGRESS'
  const dirty = JSON.stringify(answers) !== JSON.stringify(attempt.answers)
  async function save(submit = false) { setBusy(true); setError(''); setSuccess(''); try { const saved = await service.save(attempt.id, answers); setAttempt(saved); if (submit) { setAttempt(await service.submit(attempt.id)); setConfirm(false) } else setSuccess(tr("Progress saved. You can return to this assessment later.")) } catch (e) { setError(apiFailure(e).message) } finally { setBusy(false) } }
  return <div className="grid items-start gap-6 lg:grid-cols-[1fr_280px]"><div className="space-y-6"><Feedback error={error} success={success} /><section className="surface"><div className="flex flex-wrap justify-between gap-3"><span className="badge">{tr(words(attempt.status))}</span><span className="text-sm text-slate-500">{complete}{' '}{tr("of")}{' '}{questions.length}{' '}{tr("answered")}</span></div><h2 className="mt-5 text-xl font-bold">{attempt.assessment.title}</h2><progress className="mt-5 h-2 w-full accent-indigo-600" value={complete} max={questions.length} aria-label={tr("Assessment progress")} /></section>
    {attempt.result ? <ResultSummary result={attempt.result} /> : !editable && <section className="rounded-2xl bg-sky-50 p-6"><h2 className="text-lg font-bold">{tr("Submitted. Your evaluator takes it from here.")}</h2><p className="mt-3 leading-relaxed text-slate-600">{tr("Your answers are saved and locked. Your score and feedback appear here after the evaluator releases them.")}</p><Link className="mt-4 inline-block font-semibold text-indigo-700" to="/candidate/bookings">{tr("Book a conversation →")}</Link></section>}
    {q && <fieldset className="surface" disabled={!editable || busy}><legend className="sr-only">{tr("Question")}{' '}{index + 1}</legend><p className="eyebrow">{tr("Question")}{' '}{index + 1} / {questions.length}</p><h3 className="my-5 text-xl font-semibold leading-relaxed">{q.prompt}</h3><div className="space-y-3">{q.options.map((option, i) => { const letter = 'ABCD'[i] as Option; return <label key={letter} className={`flex min-h-14 cursor-pointer items-center gap-3 rounded-xl border p-4 ${answers[q.id] === letter ? 'border-indigo-500 bg-indigo-50' : 'border-slate-200 hover:bg-slate-50'}`}><input type="radio" name={`question-${q.id}`} value={letter} checked={answers[q.id] === letter} onChange={() => { setAnswers({ ...answers, [q.id]: letter }); setSuccess(''); setConfirm(false) }} className="h-4 w-4 shrink-0 accent-indigo-600" /><span className="font-semibold text-slate-500">{letter}</span><span>{option}</span></label> })}</div></fieldset>}
    <div className="flex flex-wrap justify-between gap-3"><button className="workspace-link bg-white" disabled={index === 0 || busy} onClick={() => setIndex(i => i - 1)}>{tr("← Previous")}</button><button className="workspace-link bg-white" disabled={index >= questions.length - 1 || busy} onClick={() => setIndex(i => i + 1)}>{tr("Next question →")}</button></div>
    {editable && confirm && <section role="alert" className="surface border-indigo-200"><h3 className="font-bold">{tr("Submit all")}{' '}{complete}{' '}{tr("answers?")}</h3><p className="my-4 text-sm text-slate-600">{tr("This saves your latest choices and locks the attempt for review. You cannot change your answers afterwards.")}</p><div className="flex flex-wrap gap-3"><button className="button-primary" disabled={busy} onClick={() => void save(true)}>{busy ? tr("Submitting…") : tr("Confirm submission")}</button><button className="workspace-link" disabled={busy} onClick={() => setConfirm(false)}>{tr("Keep reviewing")}</button></div></section>}
  </div><aside className="surface lg:sticky lg:top-6"><h2 className="font-bold">{tr("Your progress")}</h2><div className="my-5 grid grid-cols-4 gap-2">{questions.map((v, i) => <button key={v.id} aria-label={`Question ${i + 1}${answers[v.id] ? ', answered' : ', unanswered'}`} aria-current={i === index ? 'step' : undefined} className={`rounded-xl border py-3 font-semibold ${i === index ? 'border-indigo-600 ring-2 ring-indigo-100' : 'border-slate-200'} ${answers[v.id] ? 'bg-indigo-50 text-indigo-700' : 'bg-white'}`} onClick={() => setIndex(i)}>{i + 1}</button>)}</div>{editable && <><p className="mb-4 text-sm text-slate-500" role="status">{dirty ? tr("You have unsaved changes.") : tr("All current choices are saved.")}</p><button className="button-primary w-full" disabled={busy} onClick={() => void save()}>{busy ? tr("Saving…") : tr("Save progress")}</button><button className="workspace-link mt-3 w-full bg-slate-100" disabled={busy || complete !== questions.length} onClick={() => setConfirm(true)}>{tr("Review & submit")}</button><p className="mt-4 text-xs text-slate-500">{tr("Answer every question to submit.")}</p></>}<Link className="mt-5 inline-block text-sm font-semibold text-indigo-700" to="/candidate/assessments">{tr("Back to assessments")}</Link></aside></div>
}
