import { useState } from 'react'
import { useAuth } from '../auth/useAuth'
import { assessmentApi as service, time, type Slot } from './api'
import { Workspace, LoadState, Feedback, Empty, Field } from '../marketplace/shared'
import { useLoad, words } from '../marketplace/useLoad'
import { apiFailure } from '../../services/api'
const candidateLoad = () => Promise.all([service.slots(), service.bookings()])
const evaluatorLoad = () => Promise.all([service.ownSlots(), service.appointments()])
export function BookingPage() {
  const [now] = useState(() => Date.now())
  const { user } = useAuth(), evaluator = user?.role === 'EVALUATOR', state = useLoad(evaluator ? evaluatorLoad : candidateLoad)
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [success, setSuccess] = useState(''), [selected, setSelected] = useState<Slot | null>(null), [purpose, setPurpose] = useState('CONSULTATION'), [notes, setNotes] = useState(''), [start, setStart] = useState(''), [end, setEnd] = useState(''), [capacity, setCapacity] = useState('1'), [cancelId, setCancelId] = useState<number | null>(null)
  async function act(fn: () => Promise<unknown>, message: string) { setBusy(true); setError(''); setSuccess(''); try { await fn(); setSelected(null); setCancelId(null); setSuccess(message); state.reload() } catch (e) { setError(apiFailure(e).message) } finally { setBusy(false) } }
  const slots = state.data?.[0] ?? [], bookings = state.data?.[1] ?? []
  return <Workspace title={evaluator ? 'Time for meaningful conversations' : 'Your next conversation'} subtitle={evaluator ? 'Publish consultation and interview slots. Times are displayed in your local timezone.' : 'Book a consultation or interview with an evaluator. All times are shown in your local timezone.'}><Feedback error={error} success={success} /><LoadState {...state} />
    {evaluator && <form className="surface mb-6" onSubmit={e => { e.preventDefault(); if (new Date(end) <= new Date(start)) { setError('End time must be after the start time.'); return } void act(() => service.createSlot(new Date(start).toISOString(), new Date(end).toISOString(), Number(capacity)), 'Appointment slot published.') }}><h2 className="mb-5 text-xl font-bold">Publish a slot</h2><fieldset disabled={busy} className="grid items-end gap-4 md:grid-cols-4"><Field name="slot-start" label="Starts" type="datetime-local" required value={start} onChange={setStart} /><Field name="slot-end" label="Ends" type="datetime-local" required value={end} onChange={setEnd} /><div><label className="field-label" htmlFor="capacity">Capacity *</label><input className="form-input" id="capacity" type="number" min="1" max="20" required value={capacity} onChange={e => setCapacity(e.target.value)} /></div><button className="button-primary">{busy ? 'Publishing…' : 'Publish slot'}</button></fieldset></form>}
    {selected && <form className="surface mb-6 border-indigo-200" onSubmit={e => { e.preventDefault(); void act(() => service.book(selected.id, purpose, notes), 'Your appointment is booked.') }}><h2 className="text-xl font-bold">Confirm your appointment</h2><p className="my-4 text-sm text-slate-500">{time(selected.startTime)} → {time(selected.endTime)}</p><fieldset disabled={busy} className="space-y-4"><div><label className="field-label" htmlFor="purpose">Purpose</label><select id="purpose" className="form-input" value={purpose} onChange={e => setPurpose(e.target.value)}><option value="CONSULTATION">Consultation · পরামর্শ</option><option value="INTERVIEW">Interview · সাক্ষাৎকার</option></select></div><Field name="booking-notes" label="Anything your evaluator should know?" multiline maxLength={2000} value={notes} onChange={setNotes} /><div className="flex flex-wrap gap-3"><button className="button-primary">{busy ? 'Booking…' : 'Confirm booking'}</button><button type="button" className="workspace-link" onClick={() => setSelected(null)}>Cancel</button></div></fieldset></form>}
    {state.data && <div className="grid items-start gap-6 lg:grid-cols-2"><section className="surface"><h2 className="mb-5 text-xl font-bold">{evaluator ? 'Your published slots' : 'Available times'}</h2>{!slots.length ? <Empty title={evaluator ? 'Publish your first slot' : 'No available times yet'}>{evaluator ? 'Choose a future date and capacity above to welcome candidates.' : 'Check back when an evaluator publishes new appointment slots.'}</Empty> : <div className="space-y-4">{slots.map(s => <article className="rounded-xl border border-slate-200 p-5" key={s.id}><p className="font-semibold">{time(s.startTime)}</p><p className="mt-2 text-sm text-slate-500">Until {time(s.endTime)}</p><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><span className="badge">{!s.active ? 'Closed' : new Date(s.startTime).getTime() <= now ? 'Past slot' : `${s.remaining} / ${s.capacity} places available`}</span>{evaluator ? <button className="workspace-link bg-slate-100" disabled={busy || !s.active || s.remaining !== s.capacity} onClick={() => void act(() => service.closeSlot(s.id), 'Slot closed.')}>Close slot</button> : <button className="button-primary" disabled={busy || s.remaining < 1} onClick={() => { setSelected(s); setNotes(''); setError(''); window.scrollTo({ top: 0, behavior: 'smooth' }) }}>{s.remaining ? 'Choose time' : 'Full'}</button>}</div></article>)}</div>}</section><section className="surface"><h2 className="mb-5 text-xl font-bold">{evaluator ? 'Candidate appointments' : 'Your bookings'}</h2>{!bookings.length ? <Empty title="No appointments yet">Confirmed bookings and cancellations will appear here.</Empty> : <div className="space-y-4">{bookings.map(b => <article className="rounded-xl border border-slate-200 p-5" key={b.id}><div className="flex flex-wrap justify-between gap-3"><h3 className="font-bold">{evaluator ? b.candidateName : words(b.purpose)}</h3><span className="badge">{words(b.status)}</span></div><p className="mt-3 text-sm">{time(b.slot.startTime)}</p><p className="mt-1 text-sm text-slate-500">Until {time(b.slot.endTime)} · {words(b.purpose)}</p>{b.notes && <p className="mt-4 whitespace-pre-wrap break-words text-sm text-slate-600">{b.notes}</p>}{!evaluator && b.status === 'BOOKED' && new Date(b.slot.startTime).getTime() > now && (cancelId === b.id ? <div className="mt-4 rounded-xl bg-rose-50 p-4"><p className="mb-3 text-sm">Cancel this appointment and free your place?</p><button className="workspace-link text-rose-700" disabled={busy} onClick={() => void act(() => service.cancel(b.id), 'Appointment cancelled. You can choose a new time.')}>Confirm cancellation</button><button className="workspace-link" disabled={busy} onClick={() => setCancelId(null)}>Keep booking</button></div> : <button className="mt-4 text-sm font-semibold text-rose-700" disabled={busy} onClick={() => setCancelId(b.id)}>Cancel appointment</button>)}</article>)}</div>}</section></div>}
  </Workspace>
}
