import { notificationDestination } from './notificationNavigation'
import { useTradeText } from '../trade/useTradeText'
import { Modal } from '../../components/Modal'
import { useEffect, useState } from 'react'
import { Link } from 'react-router'
import { useAuth } from '../auth/useAuth'
import { api, apiFailure } from '../../services/api'
import { marketplace } from '../marketplace/api'
import { useLoad, words } from '../marketplace/useLoad'
import { Workspace, LoadState, Feedback, Empty, Field, Stat } from '../marketplace/shared'
import { ReadinessCard } from '../trade/ReadinessCard'
import { managed, dateTime, type Placement, type Replacement } from './api'

function Chip({ value }: { value?: string | null }) { const tr = useTradeText(); const safeValue = value ?? 'UNKNOWN'; return <span className={`badge ${['ON_TIME', 'ACTIVE', 'COMPLETED'].includes(safeValue) ? 'bg-emerald-50 text-emerald-800' : ['BREACHED', 'FAILED', 'TERMINATED'].includes(safeValue) ? 'bg-rose-50 text-rose-800' : 'bg-indigo-50 text-indigo-800'}`}>{tr(words(safeValue))}</span> }
const placementsLoader = () => Promise.all([managed.placements(), managed.replacements()])
export function PlacementsPage() {
  const { user } = useAuth()
  return user?.role === 'CANDIDATE' ? <CandidatePlacementHistory /> : <ManagedPlacementsPage />
}
function CandidatePlacementHistory() {
  const tr = useTradeText(), state = useLoad(managed.history)
  const date = (value: string) => new Date(value.length === 10 ? `${value}T00:00:00` : value).toLocaleDateString()
  return <Workspace title={tr('Placement history')} subtitle={tr('Your employment history and current placements.')}><LoadState {...state} />{state.data && <>
    <div className="mb-6 grid gap-4 sm:grid-cols-2"><Stat label={tr('Active placements')} value={state.data.filter(p => p.status === 'ACTIVE').length} /><Stat label={tr('Past placements')} value={state.data.filter(p => ['COMPLETED', 'TERMINATED'].includes(p.status)).length} /></div>
    {!state.data.length && <Empty title={tr('No placements yet')}>{tr('Your employment history will appear here.')}</Empty>}
    <div className="grid gap-5 lg:grid-cols-2">{state.data.map(p => <article key={p.id} className="surface"><h2 className="text-2xl font-bold">{p.job || p.skill}</h2><p className="mt-2 text-slate-600">{p.company}</p><dl className="mt-5 space-y-3 text-sm"><div><dt className="inline font-semibold">{tr('Skill')}: </dt><dd className="inline">{p.skill}</dd></div><div><dt className="inline font-semibold">{tr('Started')}: </dt><dd className="inline">{date(p.startDate)}</dd></div><div><dt className="inline font-semibold">{tr('Ended')}: </dt><dd className="inline">{p.endDate ? date(p.endDate) : ['COMPLETED', 'TERMINATED'].includes(p.status) ? tr('Not recorded') : '—'}</dd></div><div><dt className="inline font-semibold">{tr('Status')}: </dt><dd className="inline"><Chip value={p.status} /></dd></div></dl></article>)}</div>
  </>}</Workspace>
}
function ManagedPlacementsPage() {
  const tr = useTradeText()

  const { user } = useAuth(), employer = user?.role === 'EMPLOYER'
  const state = useLoad(placementsLoader)
  const [now, setNow] = useState(Date.now)
  useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer) }, [])
  const [selected, setSelected] = useState<Placement | null>(null), [reason, setReason] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('')
  const [cancelling, setCancelling] = useState<number | null>(null)
  async function cancelRequest() {
    setBusy(true); setError('')
    try { await api.post(`/replacements/${cancelling}/cancel`); setCancelling(null); state.reload() } catch (e) { setError(apiFailure(e).message) } finally { setBusy(false) }
  }
  const [ending, setEnding] = useState<{ p: Placement; action: string } | null>(null)
  async function request() {
    if (!selected) return
    setBusy(true); setError('')
    try { await api.post('/replacements', { placementId: selected.id, reason }); setSelected(null); setReason(''); state.reload() } catch (e) { setError(apiFailure(e).message) } finally { setBusy(false) }
  }
  async function end() {
    if (!ending) return
    setBusy(true); setError('')
    try { await api.post(`/placements/${ending.p.id}/${ending.action}`); setEnding(null); state.reload() } catch (e) { setError(apiFailure(e).message) } finally { setBusy(false) }
  }
  return <Workspace title={tr("Managed placements")} subtitle={tr("A clear view of every working relationship, its coverage and its next step.")}><LoadState {...state} /><Feedback error={!selected && !ending && !cancelling ? error : ''} />{state.data && <>
    <div className="mb-6 grid gap-4 sm:grid-cols-3"><Stat label={tr("Active placements")} value={state.data[0].filter(p => p.status === 'ACTIVE').length} />{user?.role !== 'CANDIDATE' && <><Stat label={tr("Replacement requests")} value={state.data[1].length} /><Stat label={tr("Replacements on time")} value={state.data[1].filter(r => r.slaStatus === 'ON_TIME').length} /></>}</div>
    {!state.data[0].length && <Empty title={tr("Your next placement starts here")}>{employer ? <Link to="/employer/candidates" className="text-indigo-700 underline">Open a job shortlist to hire a candidate.</Link> : tr("Complete your profile and assessments. Your managed placements will appear here.")}</Empty>}
    <div className="grid gap-5 lg:grid-cols-2">{state.data[0].map(p => {
      const activeRequest = state.data?.[1].find(r => r.placement.id === p.id && !['FAILED', 'COMPLETED', 'CANCELLED'].includes(r.status))
      const covered = p.guaranteeEligible && p.guaranteeExpiresAt && new Date(p.guaranteeExpiresAt).getTime() > now
      const unavailable = p.status !== 'ACTIVE' ? `${words(p.status)} placements are not eligible for replacement.`
        : activeRequest ? 'A replacement request is already active for this placement. View or cancel the existing request before creating another.'
        : !p.guaranteeEligible ? 'No replacement guarantee is included with this placement.'
        : !p.guaranteeExpiresAt ? 'This placement has no stored guarantee deadline.'
        : !covered ? 'Your free replacement guarantee has expired. Create a new job post to hire another candidate.' : null
      return <article key={p.id} className="surface">
        <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><p className="eyebrow">{tr("Placement #")} {p.id}</p><Chip value={p.status} /></div>
        <h2 className="text-2xl font-bold">{p.candidateName}</h2><p className="mt-2 text-slate-600">{p.skill} · {p.company}</p><p className="mt-2 text-sm text-slate-500">{p.job} · {tr("Started")} {p.startDate}</p>
        <div className="my-5 rounded-xl bg-slate-50 p-4 text-sm">{p.guaranteeEligible ? <><strong>{p.guaranteeDays != null ? `Free replacement is guaranteed within ${p.guaranteeDays} days.` : tr("Replacement guarantee")}</strong>{p.guaranteeExpiresAt && <p className="mt-1">Eligible until: {dateTime(p.guaranteeExpiresAt)}</p>}</> : <p>{tr("Standard placement · no replacement guarantee")}</p>}</div>
        {employer && unavailable && <p className="mb-4 text-sm text-slate-600">{tr(unavailable)}</p>}
        {employer && p.status === 'ACTIVE' && <div className="flex flex-wrap gap-2">{!unavailable && <button className="button-primary" onClick={() => { setError(''); setSelected(p) }}>Request replacement</button>}{activeRequest && <><Link className="button-secondary" to={`/${user?.role.toLowerCase()}/replacements`}>View replacement</Link><button className="button-secondary" disabled={busy} onClick={() => { setError(''); setCancelling(activeRequest.id) }}>Cancel replacement request</button></>}<button className="button-secondary" disabled={!!activeRequest} onClick={() => { setError(''); setEnding({ p, action: 'complete' }) }}>{tr("Complete")}</button><button className="button-secondary" disabled={!!activeRequest} onClick={() => { setError(''); setEnding({ p, action: 'terminate' }) }}>Terminate</button></div>}
      </article>
    })}</div>{user?.role !== 'CANDIDATE' && <div className="mt-8"><Link className="button-secondary" to={`/${user?.role.toLowerCase()}/replacements`}>{tr("View replacement timelines →")}</Link></div>}
  </>}{cancelling && <Modal title="Cancel replacement request?" close={() => { if (!busy) setCancelling(null) }}><p className="mb-5 text-sm text-slate-600">Any reserved worker will be released and any unused free replacement vacancy will close. Your original guarantee deadline stays unchanged.</p><Feedback error={error} /><div className="flex gap-3"><button disabled={busy} className="button-primary" onClick={() => void cancelRequest()}>{busy ? 'Cancelling…' : 'Cancel replacement request'}</button><button disabled={busy} className="button-secondary" onClick={() => setCancelling(null)}>Go back</button></div></Modal>}{selected && <Modal title="Request a replacement" close={() => { if (!busy) setSelected(null) }}><form onSubmit={e => { e.preventDefault(); void request() }}><p className="mb-5 text-sm leading-relaxed text-slate-600">Replace {selected.candidateName}{' '}{tr("for")}{' '}{selected.skill}. {selected.candidateType === 'TECH' ? 'We will publish a free replacement vacancy using the original job details. Candidates apply and you hire through the normal workflow.' : 'We will check eligible workers in queue order and begin a separate 24-hour operational target. Availability is confirmed before activation.'}</p><Field name="reason" label="Reason for replacement" value={reason} onChange={setReason} required multiline maxLength={2000} /><div className="mt-4"><Feedback error={error} /></div><div className="mt-5 flex flex-wrap gap-3"><button disabled={busy || !reason.trim()} className="button-primary">{busy ? 'Requesting…' : 'Request replacement'}</button><button type="button" disabled={busy} className="button-secondary" onClick={() => setSelected(null)}>{tr("Cancel")}</button></div></form></Modal>}{ending && <Modal title={`${ending.action === 'complete' ? tr("Complete") : 'Terminate'} placement?`} close={() => { if (!busy) setEnding(null) }}><p className="mb-5 text-slate-600">This ends the active placement for {ending.p.candidateName}. This action cannot be undone.</p><Feedback error={error} /><div className="flex gap-3"><button className="button-primary" disabled={busy} onClick={() => void end()}>{busy ? tr("Saving…") : 'Confirm'}</button><button className="button-secondary" disabled={busy} onClick={() => setEnding(null)}>Go back</button></div></Modal>}</Workspace>
}
function ReplacementCard({ r, employer, act, busy, now }: { r: Replacement; employer: boolean; act: (id: number, action: string) => void; busy: boolean; now: number }) {
  const tr = useTradeText()

  const tech = r.placement.candidateType === 'TECH'
  const remaining = !tech && r.targetCompletionAt ? new Date(r.targetCompletionAt).getTime() - now : null
  const elapsed = remaining != null ? Math.max(0, Math.min(100, (now - new Date(r.requestedAt).getTime()) / 86400000 * 100)) : 0
  const done = r.status === 'COMPLETED', failed = r.status === 'FAILED', cancelled = r.status === 'CANCELLED'
  const unresolved = !done && !failed && !cancelled
  const legacyTechFailure = tech && failed && (r.failureReason === 'No eligible candidates are currently available in this skill queue.' || r.failureReason?.startsWith('This legacy Tech request used queue matching.'))
  const sla = r.slaStatus == null ? null : !done && remaining != null && remaining < 0 ? 'BREACHED' : r.slaStatus
  const steps = tech ? ["Request received", "Free replacement job created", "Hiring in progress", "Replacement hired"] : [tr("Request received"), r.status === 'WAITING_FOR_CANDIDATE' ? "Waiting for candidate" : tr("Matching queue"), tr("Candidate selected"), tr("Accepted"), tr("Replacement active")]
  const stage = cancelled ? -1 : tech ? done ? 3 : r.freeReplacementJobId ? 2 : 0 : done ? 4 : r.status === 'ACCEPTED' ? 3 : r.selectedCandidate ? 2 : 1
  return <article className="surface overflow-hidden"><div className="flex flex-wrap justify-between gap-3"><p className="eyebrow">{tr("Replacement #")}{' '}{r.id}{' '}{tr("· Placement #")}{' '}{r.placement.id}</p><div className="flex gap-2"><Chip value={r.status} />{!tech && !cancelled && <Chip value={sla} />}</div></div><h2 className="mt-4 text-2xl font-bold">{r.placement.skill}{' '}{tr("continuity")}</h2><p className="mt-2 text-sm text-slate-500">{r.placement.company}{' '}{tr("· Replacing")}{' '}{r.placement.candidateName}</p><p className="mt-2 text-sm text-slate-600">Original job: {r.placement.job || 'Managed placement'} · {tech ? 'Tech & Corporate' : 'Trade'}</p><p className="mt-2 text-sm text-slate-600">Guarantee expiry: {r.placement.guaranteeExpiresAt ? dateTime(r.placement.guaranteeExpiresAt) : 'No replacement guarantee'}</p><p className="mt-4 break-words text-slate-600">{r.reason}</p>
    {!tech && !cancelled && r.targetCompletionAt && remaining != null && <div className="my-6 rounded-2xl bg-slate-900 p-6 text-white"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-widest text-slate-300">{tr("24-hour operational target")}</p><p className="mt-3 text-3xl font-bold tabular-nums">{done ? sla === 'ON_TIME' ? tr("Delivered on time") : sla === 'BREACHED' ? tr("Completed after target") : tr("Completed") : remaining <= 0 ? tr("Target exceeded") : `${Math.floor(remaining / 3600000)} ${tr('hours')} ${Math.floor(remaining % 3600000 / 60000)} ${tr('minutes remaining')}`}</p></div><span className="text-sm text-slate-300">{done && r.actualCompletionAt ? dateTime(r.actualCompletionAt) : `${tr('Due')} ${dateTime(r.targetCompletionAt)}`}</span></div><div role="progressbar" aria-label={tr("24-hour target elapsed")} aria-valuenow={Math.round(done ? 100 : elapsed)} aria-valuemin={0} aria-valuemax={100} className="mt-5 h-2 overflow-hidden rounded-full bg-slate-700"><div className={`h-full rounded-full transition-all ${sla === 'BREACHED' ? 'bg-rose-400' : 'bg-teal-400'}`} style={{ width: `${done ? 100 : elapsed}%` }} /></div><p className="mt-3 text-xs text-slate-300">{tr("Started")}{' '}{dateTime(r.requestedAt)}{' '}{tr(". Retrying keeps this original deadline.")}</p></div>}
    {tech && <div className="my-6 rounded-xl bg-indigo-50 p-5"><p>Tech & Corporate replacements use a free vacancy and normal applications, evaluation and hiring. The Trade 24-hour matching target does not apply.</p>{r.freeReplacementJobId && <p className="mt-3 font-semibold">Free replacement job #{r.freeReplacementJobId} · Publication payment waived</p>}{employer && r.freeReplacementJobId && unresolved && <Link className="button-primary mt-4" to={`/employer/jobs/${r.freeReplacementJobId}/applications`}>Review applicants & hire</Link>}</div>}
    <ol aria-label={tr("Replacement progress")} className="mb-6 grid gap-3 sm:grid-cols-5">{steps.map((label, i) => <li key={label} className={`rounded-xl border p-3 text-sm ${i <= stage ? 'border-teal-200 bg-teal-50 text-teal-950' : 'border-slate-200 text-slate-500'}`}><span className="mb-2 grid size-7 place-items-center rounded-full bg-white font-bold" aria-hidden="true">{i < stage ? '✓' : i + 1}</span>{label}{i === stage && <span className="mt-1 block text-xs font-semibold">{failed ? tr("Needs attention") : done ? tr("Complete") : tr("Current step")}</span>}</li>)}</ol>
    {r.selectedCandidate && <div className="mb-5 flex items-center gap-4 rounded-xl border border-indigo-100 bg-indigo-50 p-5"><span aria-hidden="true" className="grid size-12 shrink-0 place-items-center rounded-xl bg-white text-xl font-bold text-indigo-700">{r.selectedCandidate.name.slice(0, 1)}</span><div><p className="text-xs font-bold uppercase tracking-wide text-indigo-700">{done ? tr("Replacement worker") : tech ? "Selected applicant" : tr("Selected from the eligible FIFO queue")}</p><h3 className="mt-1 text-lg font-bold">{r.selectedCandidate.name}</h3><p className="text-sm text-slate-600">{r.selectedCandidate.skill} · {r.selectedCandidate.location || tr("Location not provided")}</p></div></div>}
    {r.failureReason && <p role="status" className="mb-5 rounded-xl bg-amber-50 p-4 text-sm text-amber-900">{tech && r.failureReason === 'No eligible candidates are currently available in this skill queue.' ? 'This legacy Tech request used queue matching. Start a new request from the placement while its guarantee is valid.' : tr(r.failureReason)}</p>}{done && r.replacementPlacementId != null && <p className="mb-4 font-semibold text-emerald-800">{tr("Placement #")}{' '}{r.replacementPlacementId}{' '}{tr("is active. The original placement is marked replaced.")}</p>}
    {employer && <div className="flex flex-wrap gap-3">{!tech && r.status === 'CANDIDATE_SELECTED' && <button className="button-primary" disabled={busy} onClick={() => act(r.id, 'accept')}>Confirm agreed candidate</button>}{!tech && r.status === 'ACCEPTED' && <button className="button-primary" disabled={busy} onClick={() => act(r.id, 'complete')}>Activate replacement</button>}{!tech && r.status === 'WAITING_FOR_CANDIDATE' && r.placement.status === 'ACTIVE' && <button className="button-primary" disabled={busy} onClick={() => act(r.id, 'retry')}>Retry matching</button>}{employer && (failed || cancelled) && r.placement.status === 'ACTIVE' && r.placement.guaranteeEligible && r.placement.guaranteeExpiresAt && new Date(r.placement.guaranteeExpiresAt).getTime() > now && <Link className="button-secondary" to="/employer/placements">View placement & request again</Link>}{(unresolved || legacyTechFailure) && <button className="button-secondary" disabled={busy} onClick={() => act(r.id, 'cancel')}>Cancel replacement request</button>}</div>}{employer && !tech && r.status === 'CANDIDATE_SELECTED' && <p className="mt-3 text-xs text-slate-500">Confirm after both parties agree. This showcase records employer confirmation.</p>}
  </article>
}
export function ReplacementsPage() {
  const tr = useTradeText()

  const { user } = useAuth(), state = useLoad(managed.replacements)
  const [now, setNow] = useState(Date.now), [busy, setBusy] = useState(false), [error, setError] = useState(''), [success, setSuccess] = useState('')
  const [confirm, setConfirm] = useState<{ id: number; action: string } | null>(null)
  useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 10000); return () => clearInterval(timer) }, [])
  async function act(id: number, action: string) {
    setBusy(true); setError(''); setSuccess('')
    try { const r = await api.post<Replacement>(`/replacements/${id}/${action}`); setConfirm(null); setSuccess(`Request #${id}: ${words(r.data.status)}. ${r.data.status === 'CANDIDATE_SELECTED' && action === 'complete' ? 'Eligibility changed; please confirm the newly selected worker.' : ''}`); state.reload() } catch (e) { setError(apiFailure(e).message) } finally { setBusy(false) }
  }
  return <Workspace title={tr("Continuity, with a clear timeline")} subtitle={tr("Tech & Corporate: free repost and normal hiring. Trade: managed FIFO matching with a separate 24-hour operational target.")}><div className="mb-6 flex flex-wrap gap-3"><button className="button-secondary" disabled={state.loading || busy} onClick={state.reload}>{tr("Refresh status")}</button><Link className="button-secondary" to={`/${user?.role.toLowerCase()}/placements`}>{tr("View placements")}</Link></div><Feedback error={!confirm ? error : ''} success={success} /><LoadState {...state} />{state.data && !state.data.length && <Empty title={tr("No replacement requests yet")}>{tr("Your replacement requests and progress will appear here.")}{' '}{user?.role === 'EMPLOYER' && 'Start from an active covered placement.'}</Empty>}<div className="space-y-6">{state.data?.map(r => <ReplacementCard key={r.id} r={r} employer={user?.role === 'EMPLOYER'} now={now} busy={busy} act={(id, action) => { setError(''); setConfirm({ id, action }) }} />)}</div>{confirm && <Modal title={confirm.action === 'cancel' ? 'Cancel this replacement?' : confirm.action === 'complete' ? 'Activate the replacement?' : confirm.action === 'accept' ? 'Confirm candidate agreement?' : 'Retry queue matching?'} close={() => { if (!busy) setConfirm(null) }}><p className="mb-5 text-sm text-slate-600">{confirm.action === 'cancel' ? 'Any reserved worker will be released and any unused free replacement vacancy will close. The original guarantee deadline stays unchanged.' : confirm.action === 'complete' ? 'The new placement will become active and the original placement will be marked replaced.' : confirm.action === 'accept' ? 'Confirm that the employer and selected worker have agreed to this placement.' : 'We will check the queue again using the original request deadline.'}</p><Feedback error={error} /><div className="flex gap-3"><button disabled={busy} className="button-primary" onClick={() => void act(confirm.id, confirm.action)}>{busy ? 'Updating…' : 'Confirm'}</button><button disabled={busy} className="button-secondary" onClick={() => setConfirm(null)}>Go back</button></div></Modal>}</Workspace>
}
const queueSetup = () => Promise.all([managed.queue(), marketplace.profile()])
export function QueuePage() {
  const tr = useTradeText()

  const state = useLoad(queueSetup), [skill, setSkill] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState(''), [success, setSuccess] = useState('')
  async function act(path: string, body?: object) { setBusy(true); setError(''); setSuccess(''); try { await api.post(path, body); setSuccess(body ? tr("সফলভাবে তালিকায় যোগ হয়েছে · You joined the queue.") : tr("You left this queue.")); state.reload() } catch (e) { setError(apiFailure(e).message) } finally { setBusy(false) } }
  return <Workspace title={tr("কাজের অপেক্ষার তালিকা · Your place in line")} subtitle={tr("Eligible TRADE workers join by skill. Position follows join time, not assessment score; currently ineligible workers are skipped during matching.")}><ReadinessCard /><LoadState {...state} /><Feedback error={error} success={success} />{state.data && <><form className="surface my-6" onSubmit={e => { e.preventDefault(); void act('/waiting-list/me', { skillId: Number(skill) }) }}><label className="field-label" htmlFor="queue-skill">{tr("দক্ষতা বেছে নিন · Choose your skill")}</label><select id="queue-skill" required className="form-input" value={skill} onChange={e => setSkill(e.target.value)}><option value="">{tr("Choose a profile skill")}</option>{state.data[1].skills.filter(s => s.category === 'TRADE').map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select><div className="mt-4 flex flex-wrap gap-3"><button className="button-primary" disabled={busy || !skill}>{tr("তালিকায় যোগ দিন · Join queue")}</button><Link className="button-secondary" to="/candidate/profile">{tr("Update skills & availability")}</Link></div></form>{!state.data[0].length && <Empty title={tr("Ready for your first queue?")}>{tr("Complete the readiness checks above, then select a skill to join.")}</Empty>}<div className="grid gap-5 md:grid-cols-2">{state.data[0].map(e => <article className="surface" key={e.id}><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">{e.skill}</p><p className="my-4 text-4xl font-bold text-indigo-700">{e.position ? `#${e.position}` : e.status === 'RESERVED' ? tr("Reserved") : tr("Exited")}</p></div><Chip value={e.status} /></div><p className="text-sm text-slate-500">{tr("Joined")}{' '}{dateTime(e.joinedAt)}</p><p className="mt-3 text-sm text-slate-600">{e.status === 'RESERVED' ? tr("An employer is confirming your placement. Check notifications for updates.") : e.exitReason || tr("Ready for matching when all eligibility checks pass.")}</p>{e.status === 'QUEUED' && <button disabled={busy} className="button-secondary mt-4" onClick={() => void act(`/waiting-list/${e.id}/leave`)}>{tr("Leave queue")}</button>}{e.status === 'RESERVED' && <Link className="button-secondary mt-4" to="/candidate/notifications">{tr("Notifications")}</Link>}</article>)}</div></>}</Workspace>
}
export function AdminQueuePage() {
  const tr = useTradeText()

  const state = useLoad(managed.adminQueue)
  return <Workspace title="The replacement waiting room" subtitle="FIFO by joined time, then entry ID. Reservations are protected across skills; eligibility is checked again at selection and activation."><LoadState {...state} /><button className="button-secondary mb-5" onClick={state.reload}>Refresh queue</button>{state.data && !state.data.length && <Empty title="The waiting room is empty">Eligible TRADE candidates can join from their queue workspace.</Empty>}<div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{state.data?.map(e => <article className="surface" key={e.id}><div className="mb-4 flex justify-between gap-3"><span className="text-3xl font-bold text-indigo-700">{e.position ? `#${e.position}` : '→'}</span><Chip value={e.status} /></div><h2 className="text-lg font-bold">{e.candidateName}</h2><p className="mt-2 text-slate-600">{e.skill}</p><p className="mt-3 text-xs text-slate-500">{tr("Joined")}{' '}{dateTime(e.joinedAt)} · Entry #{e.id}</p></article>)}</div></Workspace>
}
export function NotificationsPage() {
  const tr = useTradeText()

  const state = useLoad(managed.notifications), [busy, setBusy] = useState(false), [error, setError] = useState('')
  const { user } = useAuth()
  async function read(path: string) { setBusy(true); setError(''); try { await api.post(path); state.reload() } catch (e) { setError(apiFailure(e).message) } finally { setBusy(false) } }
  return <Workspace title={tr("Notifications")} subtitle={tr("Career, training and account updates, delivered inside your workspace.")}><Feedback error={error} /><LoadState {...state} />{state.data && <><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><p className="font-semibold">{state.data.filter(n => !n.readAt).length}{' '}{tr("unread updates")}</p><button className="button-secondary" disabled={busy || !state.data.some(n => !n.readAt)} onClick={() => void read('/notifications/read-all')}>{tr("Mark all as read")}</button><button className="button-secondary" disabled={busy || state.loading} onClick={state.reload}>{tr("Refresh")}</button></div>{!state.data.length && <Empty title={tr("You’re all caught up")}>{tr("New career, training and account activity will appear here.")}</Empty>}<div className="space-y-3">{state.data.map(n => <article className={`surface ${!n.readAt ? 'border-indigo-200' : ''}`} key={n.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-bold">{!n.readAt && <span className="mr-2 inline-block size-2 rounded-full bg-indigo-600" aria-label={tr("Unread")} />}{' '}{tr(n.title)}</h2><p className="mt-2 break-words text-sm text-slate-600">{tr(n.message)}</p><time dateTime={n.createdAt} className="mt-3 block text-xs text-slate-500">{dateTime(n.createdAt)}</time></div>{!n.readAt && <button className="button-secondary" disabled={busy} onClick={() => void read(`/notifications/${n.id}/read`)}>{tr("Mark read")}</button>}</div>{user && notificationDestination(n, user.role) && <Link className="mt-4 inline-block text-sm font-semibold text-indigo-700" to={notificationDestination(n, user.role)!}>{tr("View activity →")}</Link>}</article>)}</div></>}</Workspace>
}
