import { Modal } from '../../components/Modal'
import { useEffect, useState } from 'react'
import { Link } from 'react-router'
import { useAuth } from '../auth/useAuth'
import { api, apiFailure } from '../../services/api'
import { marketplace } from '../marketplace/api'
import { useLoad, words } from '../marketplace/useLoad'
import { Workspace, LoadState, Feedback, Empty, Field, Stat } from '../marketplace/shared'
import { ReadinessCard } from '../trade/ReadinessCard'
import { managed, dateTime, type Placement, type Replacement } from './api'

function Chip({ value }: { value: string }) { return <span className={`badge ${['ON_TIME', 'ACTIVE', 'COMPLETED'].includes(value) ? 'bg-emerald-50 text-emerald-800' : ['BREACHED', 'FAILED', 'TERMINATED'].includes(value) ? 'bg-rose-50 text-rose-800' : 'bg-indigo-50 text-indigo-800'}`}>{words(value)}</span> }
const placementsLoader = () => Promise.all([managed.placements(), managed.replacements()])
export function PlacementsPage() {
  const { user } = useAuth(), employer = user?.role === 'EMPLOYER'
  const state = useLoad(placementsLoader)
  const [now] = useState(Date.now)
  const [selected, setSelected] = useState<Placement | null>(null), [reason, setReason] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('')
  const [ending, setEnding] = useState<{ p: Placement; action: string } | null>(null)
  async function request() {
    if (!selected) return
    setBusy(true); setError('')
    try { await api.post('/replacements', { placementId: selected.id, reason }); setSelected(null); setReason(''); state.reload() } catch (e) { setError(apiFailure(e).message) } finally { setBusy(false) }
  }
  async function end() {
    if (!ending) return
    setBusy(true); setError('')
    try { await api.post(`/placements/${ending.p.id}/${ending.action}`); setEnding(null); state.reload() } catch (e) { setError(apiFailure(e).message) } finally { setBusy(false) }
  }
  return <Workspace title="Managed placements" subtitle="A clear view of every working relationship, its coverage and its next step."><LoadState {...state} /><Feedback error={!selected && !ending ? error : ''} />{state.data && <>
    <div className="mb-6 grid gap-4 sm:grid-cols-3"><Stat label="Active placements" value={state.data[0].filter(p => p.status === 'ACTIVE').length} /><Stat label="Replacement requests" value={state.data[1].length} /><Stat label="Replacements on time" value={state.data[1].filter(r => r.slaStatus === 'ON_TIME').length} /></div>
    {!state.data[0].length && <Empty title="Your next placement starts here">{employer ? <Link to="/employer/candidates" className="text-indigo-700 underline">Open a job shortlist to hire a candidate.</Link> : 'Complete your profile and assessments. Your managed placements will appear here.'}</Empty>}
    <div className="grid gap-5 lg:grid-cols-2">{state.data[0].map(p => {
      const activeRequest = state.data?.[1].some(r => r.placement.id === p.id && !['FAILED', 'COMPLETED'].includes(r.status))
      const covered = p.guaranteeEligible && p.guaranteeExpiresAt && new Date(p.guaranteeExpiresAt).getTime() > now
      return <article key={p.id} className="surface"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><p className="eyebrow">Placement #{p.id}</p><Chip value={p.status} /></div><h2 className="text-2xl font-bold">{p.candidateName}</h2><p className="mt-2 text-slate-600">{p.skill} · {p.company}</p><p className="mt-2 text-sm text-slate-500">{p.job} · Started {p.startDate}</p><div className="my-5 rounded-xl bg-slate-50 p-4 text-sm">{covered ? <><strong className="text-emerald-800">30-day managed TRADE coverage</strong><p className="mt-1">Expires {dateTime(p.guaranteeExpiresAt!)}</p></> : <p>{p.guaranteeEligible ? 'The guarantee window has ended.' : 'Standard placement · no replacement guarantee'}</p>}</div>{employer && p.status === 'ACTIVE' && <div className="flex flex-wrap gap-2"><button className="button-primary" disabled={!covered || activeRequest} onClick={() => { setError(''); setSelected(p) }}>{activeRequest ? 'Replacement in progress' : 'Request replacement'}</button><button className="button-secondary" disabled={activeRequest} onClick={() => { setError(''); setEnding({ p, action: 'complete' }) }}>Complete</button><button className="button-secondary" disabled={activeRequest} onClick={() => { setError(''); setEnding({ p, action: 'terminate' }) }}>Terminate</button></div>}</article>
    })}</div><div className="mt-8"><Link className="button-secondary" to={`/${user?.role.toLowerCase()}/replacements`}>View replacement timelines →</Link></div>
  </>}{selected && <Modal title="Request a replacement" close={() => { if (!busy) setSelected(null) }}><form onSubmit={e => { e.preventDefault(); void request() }}><p className="mb-5 text-sm leading-relaxed text-slate-600">Replace {selected.candidateName} for {selected.skill}. We will check eligible workers in queue order and begin a 24-hour operational target. Availability is confirmed before activation.</p><Field name="reason" label="Reason for replacement" value={reason} onChange={setReason} required multiline maxLength={2000} /><div className="mt-4"><Feedback error={error} /></div><div className="mt-5 flex flex-wrap gap-3"><button disabled={busy || !reason.trim()} className="button-primary">{busy ? 'Finding a candidate…' : 'Request & find candidate'}</button><button type="button" disabled={busy} className="button-secondary" onClick={() => setSelected(null)}>Cancel</button></div></form></Modal>}{ending && <Modal title={`${ending.action === 'complete' ? 'Complete' : 'Terminate'} placement?`} close={() => { if (!busy) setEnding(null) }}><p className="mb-5 text-slate-600">This ends the active placement for {ending.p.candidateName}. This action cannot be undone.</p><Feedback error={error} /><div className="flex gap-3"><button className="button-primary" disabled={busy} onClick={() => void end()}>{busy ? 'Saving…' : 'Confirm'}</button><button className="button-secondary" disabled={busy} onClick={() => setEnding(null)}>Go back</button></div></Modal>}</Workspace>
}
function ReplacementCard({ r, employer, act, busy, now }: { r: Replacement; employer: boolean; act: (id: number, action: string) => void; busy: boolean; now: number }) {
  const remaining = new Date(r.targetCompletionAt).getTime() - now
  const elapsed = Math.max(0, Math.min(100, (now - new Date(r.requestedAt).getTime()) / 86400000 * 100))
  const done = r.status === 'COMPLETED', failed = r.status === 'FAILED'
  const sla = !done && remaining < 0 ? 'BREACHED' : r.slaStatus
  const steps = ['Request received', 'Matching queue', 'Candidate selected', 'Accepted', 'Replacement active']
  const stage = done ? 4 : r.status === 'ACCEPTED' ? 3 : r.selectedCandidate ? 2 : 1
  return <article className="surface overflow-hidden"><div className="flex flex-wrap justify-between gap-3"><p className="eyebrow">Replacement #{r.id} · Placement #{r.placement.id}</p><div className="flex gap-2"><Chip value={r.status} /><Chip value={sla} /></div></div><h2 className="mt-4 text-2xl font-bold">{r.placement.skill} continuity</h2><p className="mt-2 text-sm text-slate-500">{r.placement.company} · Replacing {r.placement.candidateName}</p><p className="mt-4 break-words text-slate-600">{r.reason}</p>
    <div className="my-6 rounded-2xl bg-slate-900 p-6 text-white"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-widest text-slate-300">24-hour operational target</p><p className="mt-3 text-3xl font-bold tabular-nums">{done ? sla === 'ON_TIME' ? 'Delivered on time' : 'Completed after target' : remaining <= 0 ? 'Target exceeded' : `${Math.floor(remaining / 3600000)}h ${Math.floor(remaining % 3600000 / 60000)}m remaining`}</p></div><span className="text-sm text-slate-300">{done && r.actualCompletionAt ? dateTime(r.actualCompletionAt) : `Due ${dateTime(r.targetCompletionAt)}`}</span></div><div role="progressbar" aria-label="24-hour target elapsed" aria-valuenow={Math.round(done ? 100 : elapsed)} aria-valuemin={0} aria-valuemax={100} className="mt-5 h-2 overflow-hidden rounded-full bg-slate-700"><div className={`h-full rounded-full transition-all ${sla === 'BREACHED' ? 'bg-rose-400' : 'bg-teal-400'}`} style={{ width: `${done ? 100 : elapsed}%` }} /></div><p className="mt-3 text-xs text-slate-300">Started {dateTime(r.requestedAt)}. Retrying keeps this original deadline.</p></div>
    <ol aria-label="Replacement progress" className="mb-6 grid gap-3 sm:grid-cols-5">{steps.map((label, i) => <li key={label} className={`rounded-xl border p-3 text-sm ${i <= stage ? 'border-teal-200 bg-teal-50 text-teal-950' : 'border-slate-200 text-slate-500'}`}><span className="mb-2 grid size-7 place-items-center rounded-full bg-white font-bold" aria-hidden="true">{i < stage ? '✓' : i + 1}</span>{label}{i === stage && <span className="mt-1 block text-xs font-semibold">{failed ? 'Needs attention' : done ? 'Complete' : 'Current step'}</span>}</li>)}</ol>
    {r.selectedCandidate && <div className="mb-5 flex items-center gap-4 rounded-xl border border-indigo-100 bg-indigo-50 p-5"><span aria-hidden="true" className="grid size-12 shrink-0 place-items-center rounded-xl bg-white text-xl font-bold text-indigo-700">{r.selectedCandidate.name.slice(0, 1)}</span><div><p className="text-xs font-bold uppercase tracking-wide text-indigo-700">{done ? 'Replacement worker' : 'Selected from the eligible FIFO queue'}</p><h3 className="mt-1 text-lg font-bold">{r.selectedCandidate.name}</h3><p className="text-sm text-slate-600">{r.selectedCandidate.skill} · {r.selectedCandidate.location || 'Location not provided'}</p></div></div>}
    {r.failureReason && <p role="status" className="mb-5 rounded-xl bg-amber-50 p-4 text-sm text-amber-900">{r.failureReason}</p>}{done && <p className="mb-4 font-semibold text-emerald-800">Placement #{r.replacementPlacementId} is active. The original placement is marked replaced.</p>}
    {employer && <div className="flex flex-wrap gap-3">{r.status === 'CANDIDATE_SELECTED' && <button className="button-primary" disabled={busy} onClick={() => act(r.id, 'accept')}>Confirm agreed candidate</button>}{r.status === 'ACCEPTED' && <button className="button-primary" disabled={busy} onClick={() => act(r.id, 'complete')}>Activate replacement</button>}{failed && r.placement.status === 'ACTIVE' && <button className="button-primary" disabled={busy} onClick={() => act(r.id, 'retry')}>Retry matching</button>}{['CANDIDATE_SELECTED', 'ACCEPTED'].includes(r.status) && <button className="button-secondary" disabled={busy} onClick={() => act(r.id, 'cancel')}>Cancel & release worker</button>}</div>}{employer && r.status === 'CANDIDATE_SELECTED' && <p className="mt-3 text-xs text-slate-500">Confirm after both parties agree. This showcase records employer confirmation.</p>}
  </article>
}
export function ReplacementsPage() {
  const { user } = useAuth(), state = useLoad(managed.replacements)
  const [now, setNow] = useState(Date.now), [busy, setBusy] = useState(false), [error, setError] = useState(''), [success, setSuccess] = useState('')
  const [confirm, setConfirm] = useState<{ id: number; action: string } | null>(null)
  useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 10000); return () => clearInterval(timer) }, [])
  async function act(id: number, action: string) {
    setBusy(true); setError(''); setSuccess('')
    try { const r = await api.post<Replacement>(`/replacements/${id}/${action}`); setConfirm(null); setSuccess(`Request #${id}: ${words(r.data.status)}. ${r.data.status === 'CANDIDATE_SELECTED' && action === 'complete' ? 'Eligibility changed; please confirm the newly selected worker.' : ''}`); state.reload() } catch (e) { setError(apiFailure(e).message) } finally { setBusy(false) }
  }
  return <Workspace title="Continuity, with a clear timeline" subtitle="Follow every replacement from request to activation. Eligible workers are selected by queue join time, with a stable ID tie-breaker."><div className="mb-6 flex flex-wrap gap-3"><button className="button-secondary" disabled={state.loading || busy} onClick={state.reload}>Refresh status</button><Link className="button-secondary" to={`/${user?.role.toLowerCase()}/placements`}>View placements</Link></div><Feedback error={!confirm ? error : ''} success={success} /><LoadState {...state} />{state.data && !state.data.length && <Empty title="No replacement requests yet">Requests and their 24-hour timelines will appear here. {user?.role === 'EMPLOYER' && 'Start from an active covered placement.'}</Empty>}<div className="space-y-6">{state.data?.map(r => <ReplacementCard key={r.id} r={r} employer={user?.role === 'EMPLOYER'} now={now} busy={busy} act={(id, action) => { setError(''); setConfirm({ id, action }) }} />)}</div>{confirm && <Modal title={confirm.action === 'cancel' ? 'Cancel this replacement?' : confirm.action === 'complete' ? 'Activate the replacement?' : confirm.action === 'accept' ? 'Confirm candidate agreement?' : 'Retry queue matching?'} close={() => { if (!busy) setConfirm(null) }}><p className="mb-5 text-sm text-slate-600">{confirm.action === 'cancel' ? 'The reserved worker will be released. Eligible workers keep their original queue join time.' : confirm.action === 'complete' ? 'The new placement will become active and the original placement will be marked replaced.' : confirm.action === 'accept' ? 'Confirm that the employer and selected worker have agreed to this placement.' : 'We will check the queue again using the original request deadline.'}</p><Feedback error={error} /><div className="flex gap-3"><button disabled={busy} className="button-primary" onClick={() => void act(confirm.id, confirm.action)}>{busy ? 'Updating…' : 'Confirm'}</button><button disabled={busy} className="button-secondary" onClick={() => setConfirm(null)}>Go back</button></div></Modal>}</Workspace>
}
const queueSetup = () => Promise.all([managed.queue(), marketplace.profile()])
export function QueuePage() {
  const state = useLoad(queueSetup), [skill, setSkill] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState(''), [success, setSuccess] = useState('')
  async function act(path: string, body?: object) { setBusy(true); setError(''); setSuccess(''); try { await api.post(path, body); setSuccess(body ? 'সফলভাবে তালিকায় যোগ হয়েছে · You joined the queue.' : 'You left this queue.'); state.reload() } catch (e) { setError(apiFailure(e).message) } finally { setBusy(false) } }
  return <Workspace title="কাজের অপেক্ষার তালিকা · Your place in line" subtitle="Eligible TRADE workers join by skill. Position follows join time, not assessment score; currently ineligible workers are skipped during matching."><ReadinessCard /><LoadState {...state} /><Feedback error={error} success={success} />{state.data && <><form className="surface my-6" onSubmit={e => { e.preventDefault(); void act('/waiting-list/me', { skillId: Number(skill) }) }}><label className="field-label" htmlFor="queue-skill">দক্ষতা বেছে নিন · Choose your skill</label><select id="queue-skill" required className="form-input" value={skill} onChange={e => setSkill(e.target.value)}><option value="">Choose a profile skill</option>{state.data[1].skills.filter(s => s.category === 'TRADE').map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select><div className="mt-4 flex flex-wrap gap-3"><button className="button-primary" disabled={busy || !skill}>তালিকায় যোগ দিন · Join queue</button><Link className="button-secondary" to="/candidate/profile">Update skills & availability</Link></div></form>{!state.data[0].length && <Empty title="Ready for your first queue?">Complete the readiness checks above, then select a skill to join.</Empty>}<div className="grid gap-5 md:grid-cols-2">{state.data[0].map(e => <article className="surface" key={e.id}><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">{e.skill}</p><p className="my-4 text-4xl font-bold text-indigo-700">{e.position ? `#${e.position}` : e.status === 'RESERVED' ? 'Reserved' : 'Exited'}</p></div><Chip value={e.status} /></div><p className="text-sm text-slate-500">Joined {dateTime(e.joinedAt)}</p><p className="mt-3 text-sm text-slate-600">{e.status === 'RESERVED' ? 'An employer is confirming your placement. View your replacement timeline for updates.' : e.exitReason || 'Ready for matching when all eligibility checks pass.'}</p>{e.status === 'QUEUED' && <button disabled={busy} className="button-secondary mt-4" onClick={() => void act(`/waiting-list/${e.id}/leave`)}>Leave queue</button>}{e.status === 'RESERVED' && <Link className="button-secondary mt-4" to="/candidate/replacements">View selection</Link>}</article>)}</div></>}</Workspace>
}
export function AdminQueuePage() {
  const state = useLoad(managed.adminQueue)
  return <Workspace title="The replacement waiting room" subtitle="FIFO by joined time, then entry ID. Reservations are protected across skills; eligibility is checked again at selection and activation."><LoadState {...state} /><button className="button-secondary mb-5" onClick={state.reload}>Refresh queue</button>{state.data && !state.data.length && <Empty title="The waiting room is empty">Eligible TRADE candidates can join from their queue workspace.</Empty>}<div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{state.data?.map(e => <article className="surface" key={e.id}><div className="mb-4 flex justify-between gap-3"><span className="text-3xl font-bold text-indigo-700">{e.position ? `#${e.position}` : '→'}</span><Chip value={e.status} /></div><h2 className="text-lg font-bold">{e.candidateName}</h2><p className="mt-2 text-slate-600">{e.skill}</p><p className="mt-3 text-xs text-slate-500">Joined {dateTime(e.joinedAt)} · Entry #{e.id}</p></article>)}</div></Workspace>
}
export function NotificationsPage() {
  const state = useLoad(managed.notifications), [busy, setBusy] = useState(false), [error, setError] = useState('')
  const { user } = useAuth()
  async function read(path: string) { setBusy(true); setError(''); try { await api.post(path); state.reload() } catch (e) { setError(apiFailure(e).message) } finally { setBusy(false) } }
  return <Workspace title="Notifications" subtitle="Career, training and account updates, delivered inside your workspace."><Feedback error={error} /><LoadState {...state} />{state.data && <><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><p className="font-semibold">{state.data.filter(n => !n.readAt).length} unread updates</p><button className="button-secondary" disabled={busy || !state.data.some(n => !n.readAt)} onClick={() => void read('/notifications/read-all')}>Mark all as read</button></div>{!state.data.length && <Empty title="You’re all caught up">New career, training and account activity will appear here.</Empty>}<div className="space-y-3">{state.data.map(n => <article className={`surface ${!n.readAt ? 'border-indigo-200' : ''}`} key={n.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-bold">{!n.readAt && <span className="mr-2 inline-block size-2 rounded-full bg-indigo-600" aria-label="Unread" />}{n.title}</h2><p className="mt-2 break-words text-sm text-slate-600">{n.message}</p><time className="mt-3 block text-xs text-slate-500">{dateTime(n.createdAt)}</time></div>{!n.readAt && <button className="button-secondary" disabled={busy} onClick={() => void read(`/notifications/${n.id}/read`)}>Mark read</button>}</div>{user?.role !== 'EVALUATOR' && <Link className="mt-4 inline-block text-sm font-semibold text-indigo-700" to={`/${user?.role.toLowerCase()}/${n.title === 'Your next learning step' ? 'training' : n.title === 'Account status updated' || n.title.startsWith('Welcome') ? 'dashboard' : n.message.startsWith('Replacement') || n.title.toLowerCase().includes('replacement') ? 'replacements' : 'placements'}`}>View activity →</Link>}</article>)}</div></>}</Workspace>
}
