import { useState } from 'react'
import { Link, Navigate } from 'react-router'
import { marketplace, type Profile, type Skill } from '../marketplace/api'
import { Workspace, LoadState, Field, Feedback } from '../marketplace/shared'
import { useLoad } from '../marketplace/useLoad'
import { api, apiFailure } from '../../services/api'
import { VoiceInput } from './VoiceInput'
const load = () => Promise.all([marketplace.profile(), marketplace.skills()])
const labels: Record<string, string> = { Driving: 'ড্রাইভিং', 'Electrical Work': 'ইলেকট্রিক কাজ', Plumbing: 'প্লাম্বিং', Mechanics: 'মেকানিক', Delivery: 'ডেলিভারি', 'Vehicle Repair': 'গাড়ি মেরামত', 'Electrical Installation': 'ইলেকট্রিক কাজ' }
export function TradeOnboardingPage() {
  const state = useLoad(load)
  return <Workspace title="আপনার দক্ষতা, আপনার ভবিষ্যৎ" subtitle="তিনটি সহজ ধাপে পরিচিতি তৈরি করুন। Build your work profile in three simple steps."><LoadState {...state} />{!state.loading && !state.error && state.data && (state.data[0].candidateType !== 'TRADE' ? <Navigate to="/candidate/profile" replace /> : <Onboarding initial={state.data[0]} catalog={state.data[1].filter(s => s.category === 'TRADE')} />)}</Workspace>
}
function Onboarding({ initial, catalog }: { initial: Profile; catalog: Skill[] }) {
  const [p, setP] = useState({ ...initial, primaryTradeCategory: initial.primaryTradeCategory || initial.skills.find(s => s.category === 'TRADE')?.name || '' }), [step, setStep] = useState(0), [skill, setSkill] = useState(initial.skills.find(s => s.category === 'TRADE')?.id ?? 0)
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [fields, setFields] = useState<Record<string, string>>({}), [saved, setSaved] = useState(false)
  function change(key: keyof Profile, value: string) { setP(v => ({ ...v, [key]: value })); setSaved(false) }
  async function save() {
    setBusy(true); setError(''); setFields({})
    try {
      const { fullName, phone, location, bio, experienceSummary, availability, primaryTradeCategory } = p
      const updated = (await api.put<Profile>('/candidates/me', { fullName, phone, location, bio, experienceSummary, availability, primaryTradeCategory })).data
      // Profile and skill endpoints are individually retryable; keep the confirmed profile if adding a skill fails.
      setP(updated)
      if (!updated.skills.some(s => s.id === skill)) setP((await api.post<Profile>('/candidates/me/skills', { skillId: skill, proficiencyLevel: 'Practising' })).data)
      setSaved(true)
    } catch (e) { const f = apiFailure(e); setError(f.message); setFields(f.fieldErrors ?? {}); setStep(1) } finally { setBusy(false) }
  }
  return <div lang="bn" className="mx-auto max-w-4xl"><section className="mb-6 rounded-2xl bg-slate-900 p-6 text-white sm:p-8"><p className="text-sm text-teal-200">TRADE · দক্ষতার পথে</p><h2 className="my-3 text-2xl font-bold">কাজ জানেন? পরিচিতি গড়ুন।</h2><p className="text-sm leading-relaxed text-slate-300">লিখে অথবা বাংলায় বলে শুরু করুন। আপনার তথ্য যেকোনো সময় প্রোফাইলে পরিবর্তন করতে পারবেন।</p><ol className="mt-6 grid grid-cols-3 gap-3">{['পেশা · Trade', 'পরিচিতি · Profile', 'নিশ্চিত · Confirm'].map((label, i) => <li key={label} aria-current={step === i ? 'step' : undefined} className={`rounded-xl p-3 text-sm ${i <= step ? 'bg-teal-400 text-slate-950' : 'bg-white/10 text-slate-300'}`}><span className="mb-1 block font-bold">0{i + 1}</span>{label}</li>)}</ol><progress aria-label="Onboarding progress" max={3} value={saved ? 3 : step + 1} className="mt-5 h-2 w-full accent-teal-400" /></section>
    <Feedback error={error} success={saved ? 'পরিচিতি সংরক্ষিত হয়েছে। Your profile is saved.' : ''} />
    {saved ? <section className="surface text-center"><span className="text-4xl text-teal-700">✓</span><h2 className="mt-4 text-2xl font-bold">দারুণ, পরিচিতি তৈরি হয়েছে</h2><p className="my-4 text-slate-600">এবার প্ল্যাটফর্ম যাচাইয়ের তথ্য জমা দিন এবং মূল্যায়ন সম্পূর্ণ করুন। Complete verification and assessment to build your readiness.</p><Link className="button-primary" to="/candidate/verification">যাচাই শুরু করুন · Start verification →</Link><Link className="mt-4 block font-semibold text-indigo-700" to="/candidate/dashboard">ড্যাশবোর্ড · Dashboard</Link></section> : <form className="surface" onSubmit={e => { e.preventDefault(); if (step < 2) setStep(step + 1); else void save() }}><fieldset disabled={busy} className="space-y-6">
    {step === 0 && <><div><h2 className="text-xl font-bold">আপনি কোন কাজ করেন?</h2><p className="mt-2 text-sm text-slate-500">একটি প্রধান দক্ষতা বেছে নিন। Choose your main skill; add more later.</p></div><div className="grid gap-3 sm:grid-cols-2">{catalog.map(s => <button key={s.id} type="button" aria-pressed={skill === s.id} className={`min-h-24 rounded-2xl border-2 p-5 text-left transition ${skill === s.id ? 'border-teal-600 bg-teal-50' : 'border-slate-200 hover:border-teal-300'}`} onClick={() => { setSkill(s.id); change('primaryTradeCategory', s.name) }}><span className="block text-lg font-bold">{labels[s.name] ?? s.name}</span><span className="mt-2 block text-sm text-slate-600">{s.name} {skill === s.id ? '✓' : '→'}</span></button>)}</div>{!catalog.length && <p role="alert">কোনো পেশা পাওয়া যায়নি। পরে আবার চেষ্টা করুন। No active trade skills available.</p>}</>}
    {step === 1 && <><h2 className="text-xl font-bold">আপনার পরিচিতি · Your profile</h2><Field name="fullName" label="পুরো নাম · Full name" required maxLength={160} value={p.fullName} onChange={v => change('fullName', v)} error={fields.fullName} /><div className="grid gap-5 sm:grid-cols-2"><Field name="phone" label="ফোন · Phone (01…)" type="tel" required maxLength={32} value={p.phone} onChange={v => change('phone', v.replace(/[০-৯]/g, c => String('০১২৩৪৫৬৭৮৯'.indexOf(c))))} error={fields.phone} /><Field name="location" label="এলাকা · Location" required value={p.location} onChange={v => change('location', v)} error={fields.location} /></div><VoiceInput disabled={busy} onApply={v => change('experienceSummary', v)} /><Field name="experienceSummary" label="অভিজ্ঞতা লিখুন · Type your experience" required multiline maxLength={2000} value={p.experienceSummary} onChange={v => change('experienceSummary', v)} error={fields.experienceSummary} /><div><label htmlFor="trade-availability" className="field-label">কাজের জন্য প্রস্তুত? · Availability</label><select id="trade-availability" className="form-input" value={p.availability} onChange={e => change('availability', e.target.value)}><option value="AVAILABLE">হ্যাঁ, কাজ করতে প্রস্তুত · Available</option><option value="UNAVAILABLE">এখন প্রস্তুত নই · Unavailable</option></select></div></>}
    {step === 2 && <><h2 className="text-xl font-bold">দেখে নিশ্চিত করুন · Review your details</h2><dl className="grid gap-5 rounded-xl bg-slate-50 p-5 sm:grid-cols-2">{[['নাম · Name', p.fullName], ['পেশা · Trade', p.primaryTradeCategory], ['ফোন · Phone', p.phone], ['এলাকা · Location', p.location], ['অভিজ্ঞতা · Experience', p.experienceSummary], ['প্রস্তুতি · Availability', p.availability === 'AVAILABLE' ? 'প্রস্তুত · Available' : 'এখন প্রস্তুত নই · Unavailable']].map(([k, v]) => <div key={k} className="min-w-0"><dt className="text-sm text-slate-500">{k}</dt><dd className="mt-1 whitespace-pre-wrap break-words font-semibold">{v}</dd></div>)}</dl><p className="text-sm text-slate-500">এটি আপনার নিজের দেওয়া পরিচিতি। যাচাই ও মূল্যায়ন প্ল্যাটফর্ম আলাদাভাবে সম্পন্ন করবে। Platform verification and assessment are separate steps.</p></>}
    <div className="flex flex-wrap gap-3 border-t border-slate-100 pt-5">{step > 0 && <button type="button" className="button-secondary" onClick={() => setStep(step - 1)}>← পেছনে · Back</button>}<button className="button-primary grow" disabled={busy || !skill}>{busy ? 'সংরক্ষণ হচ্ছে…' : step === 2 ? 'সংরক্ষণ করুন · Save profile' : 'পরবর্তী · Continue →'}</button></div></fieldset></form>}
  </div>
}
