export const tradeBn: Readonly<Record<string, string>> = {
  "Dashboard": "ড্যাশবোর্ড",
  "Sign out": "বের হন",
  "Skip to content": "মূল পাতায় যান",
  "Main navigation": "প্রধান মেনু",
  "Verified Career home": "মূল পাতায় যান",
  "Verified Skill & Career Managed Marketplace": "যাচাইকৃত দক্ষতা ও চাকরির প্ল্যাটফর্ম",
  "Built for Bangladesh": "বাংলাদেশের জন্য তৈরি",
  "Overview": "সারসংক্ষেপ",
  "My profile": "আমার প্রোফাইল",
  "CV Builder": "সিভি তৈরি",
  "Explore Jobs": "চাকরি খুঁজুন",
  "My applications": "আমার আবেদন",
  "Verification": "ভেরিফিকেশন",
  "Assessments": "মূল্যায়ন",
  "Appointments": "সেশন বুকিং",
  "Placements": "নিয়োগ",
  "Replacements": "বিকল্প কর্মী",
  "Training": "প্রশিক্ষণ",
  "Notifications": "নোটিফিকেশন",
  "🔔 Notifications": "🔔 নোটিফিকেশন",
  "Workspace menu": "কাজের মেনু",
  "Workspace": "কাজের পাতা",
  "Mobile workspace": "মোবাইল মেনু",
  "Loading your workspace…": "তথ্য আসছে…",
  "Try again": "আবার চেষ্টা করুন",
  "Your career, in focus": "আপনার কাজের যাত্রা",
  "Build a clear profile, share your skills and keep your availability up to date.": "প্রোফাইল তৈরি করুন, দক্ষতা যোগ করুন এবং কাজের প্রস্তুতি জানান।",
  "Your core profile is complete": "আপনার প্রোফাইলের মূল তথ্য সম্পূর্ণ",
  "Let your next opportunity find you": "নতুন কাজের জন্য প্রস্তুত হোন",
  "Manage profile": "প্রোফাইল দেখুন",
  "Complete my profile": "প্রোফাইল সম্পূর্ণ করুন",
  "Core profile": "প্রোফাইলের মূল তথ্য",
  "Core profile completion": "প্রোফাইল কতটা সম্পূর্ণ",
  "Location": "এলাকা",
  "Experience": "অভিজ্ঞতা",
  "Skills": "দক্ষতা",
  "Profile photo required": "প্রোফাইলে ছবি প্রয়োজন",
  "Uploaded or built CV": "আপলোড বা তৈরি করা সিভি",
  "Trade category": "পেশার ধরন",
  "Edit built CV": "সিভি সম্পাদনা করুন",
  "Build your CV": "সিভি তৈরি করুন",
  "Profile completion is separate from verified readiness.": "প্রোফাইল সম্পূর্ণ হওয়া ও যাচাইকৃত প্রস্তুতি আলাদা বিষয়।",
  "Skills on your profile": "প্রোফাইলের দক্ষতা",
  "Availability": "কাজের প্রস্তুতি",
  "Released assessments": "প্রকাশিত মূল্যায়ন",
  "Your expertise": "আপনার দক্ষতা",
  "Add your location to help employers find you.": "নিয়োগকর্তা যেন খুঁজে পান, তাই এলাকা যোগ করুন।",
  "Add your first skill to appear in skill searches.": "দক্ষতা দিয়ে খুঁজে পেতে প্রথম দক্ষতা যোগ করুন।",
  "Edit skills and availability →": "দক্ষতা ও কাজের প্রস্তুতি বদলান →",
  "Platform review": "প্ল্যাটফর্ম যাচাই",
  "Verification is a manual platform review. An active account alone does not mean your skills or identity have been verified.": "প্ল্যাটফর্ম আপনার তথ্য ম্যানুয়ালি যাচাই করে। অ্যাকাউন্ট সক্রিয় হলেই পরিচয় বা দক্ষতা যাচাই হয়েছে এমন নয়।",
  "Your next steps": "পরবর্তী ধাপ",
  "Assessments & feedback": "মূল্যায়ন ও মতামত",
  "Start your first assessment and show employers what you know.": "প্রথম মূল্যায়ন দিয়ে আপনার দক্ষতা দেখান।",
  "Open assessments →": "মূল্যায়ন দেখুন →",
  "Next appointment": "পরবর্তী সেশন",
  "No upcoming appointment. Book time to discuss your career.": "সামনে কোনো সেশন নেই। কাজ নিয়ে কথা বলতে সময় বুক করুন।",
  "Manage appointments →": "সেশন দেখুন →",
  "Active placements": "চলমান নিয়োগ",
  "Training referrals": "প্রশিক্ষণের পরামর্শ",
  "Unread updates": "না-পড়া খবর",
  "View details →": "বিস্তারিত দেখুন →",
  "Make your skills stand out": "আপনার দক্ষতা তুলে ধরুন",
  "Tell employers what you do best. Your career track and platform review results are managed separately.": "আপনার কাজের অভিজ্ঞতা জানান। পেশার ধরন ও প্ল্যাটফর্মের যাচাই আলাদাভাবে পরিচালিত হয়।",
  "About you": "আপনার সম্পর্কে",
  "Total experience (months)": "মোট অভিজ্ঞতা (মাস)",
  "Enter completed months of experience. Keep your description above.": "কত মাস কাজ করেছেন লিখুন। উপরে অভিজ্ঞতার বিস্তারিত রাখুন।",
  "Available for work · কাজ করতে প্রস্তুত": "কাজ করতে প্রস্তুত",
  "Currently unavailable · এখন প্রস্তুত নই": "এখন প্রস্তুত নই",
  "Save profile · সংরক্ষণ": "প্রোফাইল সংরক্ষণ করুন",
  "Saving…": "সংরক্ষণ হচ্ছে…",
  "Built CV": "তৈরি করা সিভি",
  "Your built CV is empty. Add a summary or your first entry in the builder.": "সিভিতে এখনো তথ্য নেই। সিভি তৈরির পাতায় পরিচিতি বা প্রথম তথ্য যোগ করুন।",
  "Create and maintain your structured CV, then preview or print it. Your uploaded PDF stays separate.": "নিজের তথ্য দিয়ে সিভি তৈরি, সম্পাদনা ও প্রিন্ট করুন। আপলোড করা পিডিএফ আলাদা থাকবে।",
  "Open CV Builder": "সিভি তৈরি করুন",
  "Add the skills employers can search for. Proficiency is self-reported.": "নিয়োগকর্তা খুঁজতে পারেন এমন দক্ষতা যোগ করুন। দক্ষতার স্তর আপনার নিজের দেওয়া তথ্য।",
  "Remove": "সরান",
  "No skills yet. Add your first skill below.": "দক্ষতা যোগ করা হয়নি। নিচে প্রথম দক্ষতা যোগ করুন।",
  "Choose skill": "দক্ষতা বেছে নিন",
  "Select a skill": "একটি দক্ষতা বেছে নিন",
  "Experience level": "অভিজ্ঞতার স্তর",
  "Add skill": "দক্ষতা যোগ করুন",
  "Your profile has been saved.": "প্রোফাইল সংরক্ষিত হয়েছে।",
  "Skill added.": "দক্ষতা যোগ হয়েছে।",
  "Skill removed.": "দক্ষতা সরানো হয়েছে।",
  "Application:": "আবেদন:",
  "Apply": "আবেদন করুন",
  "Applying…": "আবেদন হচ্ছে…",
  "Job closed": "চাকরির আবেদন বন্ধ",
  "Search jobs": "চাকরি খুঁজুন",
  "Find your next opportunity": "আপনার পরবর্তী কাজ খুঁজুন",
  "Search jobs by title, skill, company…": "চাকরি, দক্ষতা বা প্রতিষ্ঠানের নাম লিখুন…",
  "e.g. Dhaka": "যেমন: ঢাকা",
  "Company type / sector": "প্রতিষ্ঠানের ধরন",
  "All sectors": "সব ধরনের প্রতিষ্ঠান",
  "Selected sector (unavailable)": "বেছে নেওয়া ধরন (পাওয়া যাচ্ছে না)",
  "Loading sectors…": "প্রতিষ্ঠানের ধরন আসছে…",
  "Unable to load sectors.": "প্রতিষ্ঠানের ধরন আনা যায়নি।",
  "Retry": "আবার চেষ্টা করুন",
  "Candidate track": "প্রার্থীর ধরন",
  "All tracks": "সব ধরনের প্রার্থী",
  "TECH · Professional": "পেশাজীবী",
  "TRADE · Field & household": "কারিগরি ও গৃহস্থালি কাজ",
  "Experience required (months)": "প্রয়োজনীয় অভিজ্ঞতা (মাস)",
  "Minimum months": "সর্বনিম্ন মাস",
  "Maximum months": "সর্বোচ্চ মাস",
  "Any": "যেকোনো",
  "Set maximum to 0 for first-time roles, 12 for up to 1 year, or 24 for up to 2 years.": "নতুনদের কাজের জন্য সর্বোচ্চ ০, এক বছর পর্যন্ত ১২ বা দুই বছর পর্যন্ত ২৪ মাস দিন।",
  "Sort results": "সাজানোর ক্রম",
  "Newest first": "নতুন আগে",
  "Oldest first": "পুরোনো আগে",
  "Lowest experience first": "কম অভিজ্ঞতা আগে",
  "Highest experience first": "বেশি অভিজ্ঞতা আগে",
  "Clear filters": "ফিল্টার মুছুন",
  "Select filters, then search to update results.": "ফিল্টার বেছে নিয়ে খুঁজুন বোতামে চাপ দিন।",
  "Discover professional, trade and household opportunities. Find a role that fits your skills and experience.": "পেশাজীবী, কারিগরি ও গৃহস্থালি কাজ খুঁজুন। নিজের দক্ষতা ও অভিজ্ঞতার সঙ্গে মিলিয়ে বেছে নিন।",
  "My applications →": "আমার আবেদন →",
  "opportunity": "চাকরি",
  "opportunities": "চাকরি",
  "found": "পাওয়া গেছে",
  "No jobs on this page": "এই পাতায় চাকরি নেই",
  "No matching jobs": "মিলে যায় এমন চাকরি নেই",
  "Try a broader search or clear your filters to explore available roles.": "অন্যভাবে খুঁজুন অথবা ফিল্টার মুছে সব চাকরি দেখুন।",
  "Show all jobs": "সব চাকরি দেখুন",
  "Posted": "প্রকাশিত",
  "Sector not specified": "প্রতিষ্ঠানের ধরন দেওয়া নেই",
  "View details": "বিস্তারিত দেখুন",
  "for": "জন্য",
  "Job result pages": "চাকরির ফলাফলের পাতা",
  "Previous": "আগের পাতা",
  "Next": "পরের পাতা",
  "Page": "পাতা",
  "of": "এর মধ্যে",
  "Job details": "চাকরির বিস্তারিত",
  "Review the role before submitting your application.": "আবেদনের আগে কাজের বিস্তারিত পড়ুন।",
  "← Explore Jobs": "← চাকরি খুঁজুন",
  "· Posted": "· প্রকাশিত",
  "About the role": "কাজের বিবরণ",
  "What the employer expects": "নিয়োগকর্তার প্রত্যাশা",
  "See the responsibilities and requirements above.": "উপরে কাজের দায়িত্ব ও শর্ত দেখুন।",
  "Required skill:": "প্রয়োজনীয় দক্ষতা:",
  "Track your applications and employer decisions.": "আপনার আবেদন ও নিয়োগকর্তার সিদ্ধান্ত দেখুন।",
  "Applied": "আবেদনের সময়",
  "Assessment completed": "মূল্যায়ন সম্পূর্ণ",
  "View submitted assessment": "জমা দেওয়া মূল্যায়ন দেখুন",
  "Continue assessment": "মূল্যায়ন চালিয়ে যান",
  "Start assessment": "মূল্যায়ন শুরু করুন",
  "Withdraw": "আবেদন প্রত্যাহার করুন",
  "Withdrawing…": "প্রত্যাহার হচ্ছে…",
  "Withdraw this application? It will remain in your history and cannot be submitted again.": "আবেদন প্রত্যাহার করবেন? এটি ইতিহাসে থাকবে এবং আবার জমা দিতে পারবেন না।",
  "You haven’t applied yet": "এখনো আবেদন করেননি",
  "View current openings": "চলমান চাকরি দেখুন",
  " to find a role and apply.": " এবং পছন্দের কাজে আবেদন করুন।",
  "Upload the documents on your checklist for manual platform review. There is no government NID integration.": "প্ল্যাটফর্মের ম্যানুয়াল যাচাইয়ের জন্য তালিকার কাগজপত্র আপলোড করুন। সরকারি এনআইডি সেবার সঙ্গে সংযোগ নেই।",
  "Overall verification": "ভেরিফিকেশনের অবস্থা",
  "Refresh checklist": "তালিকা হালনাগাদ করুন",
  "All required documents must be approved. Only you and authorized administrators can download your documents. Replacing a document starts a new review.": "সব আবশ্যক কাগজপত্র অনুমোদিত হতে হবে। শুধু আপনি ও অনুমোদিত অ্যাডমিন কাগজপত্র ডাউনলোড করতে পারবেন। নতুন কাগজ দিলে আবার যাচাই হবে।",
  "There are no active document requirements for your account.": "আপনার অ্যাকাউন্টের জন্য এখন কোনো কাগজপত্রের শর্ত নেই।",
  "Submission history ·": "জমা দেওয়ার ইতিহাস ·",
  "Earlier submissions are retained. Documents for requirements that no longer apply do not count toward your current checklist.": "আগের জমা রাখা আছে। এখন প্রযোজ্য নয় এমন কাগজ বর্তমান যাচাইয়ে ধরা হয় না।",
  " · Previous platform review": " · আগের প্ল্যাটফর্ম যাচাই",
  "Download": "ডাউনলোড করুন",
  "submission": "জমা",
  "Required · আবশ্যক": "আবশ্যক",
  "Optional": "ঐচ্ছিক",
  "Previous platform identity review": "আগের পরিচয় যাচাই",
  "Submitted": "জমা হয়েছে",
  "Review feedback:": "যাচাইয়ের মন্তব্য:",
  "Download document": "কাগজপত্র ডাউনলোড করুন",
  "Your previous decision has been preserved.": "আগের সিদ্ধান্ত রাখা হয়েছে।",
  "Replace / resubmit document": "কাগজপত্র বদলান / আবার জমা দিন",
  "Upload document": "কাগজপত্র আপলোড করুন",
  "PDF, JPG or PNG · Maximum 5 MB. Use fictional documents for the showcase.": "পিডিএফ, জেপিজি বা পিএনজি · সর্বোচ্চ ৫ এমবি। প্রদর্শনীর জন্য কাল্পনিক কাগজ ব্যবহার করুন।",
  "Uploading…": "আপলোড হচ্ছে…",
  "Submit replacement": "নতুন কাগজ জমা দিন",
  "Submit for review": "যাচাইয়ের জন্য জমা দিন",
  "Choose a file up to 5 MB.": "সর্বোচ্চ ৫ এমবির ফাইল বেছে নিন।",
  "Demo Payment": "ডেমো পেমেন্ট",
  "No Real Money Will Be Charged": "কোনো আসল টাকা কাটা হবে না",
  "Demo payment successful. Your appointment is confirmed.": "ডেমো পেমেন্ট সফল। আপনার সেশন নিশ্চিত হয়েছে।",
  "This is a demo payment. No real payment will be made. No bank, card or mobile banking details are needed.": "এটি শুধুমাত্র ডেমো পেমেন্ট। কোনো আসল টাকা কাটা হবে না। ব্যাংক, কার্ড বা মোবাইল ব্যাংকিংয়ের তথ্য লাগে না।",
  "Internal demo reference": "ডেমো রেফারেন্স",
  "Status": "অবস্থা",
  "Your place is confirmed only after payment succeeds, subject to current availability.": "পেমেন্ট সফল হলে আসন খালি থাকা সাপেক্ষে বুকিং নিশ্চিত হবে।",
  "Processing…": "কাজ চলছে…",
  "Complete Demo Payment": "ডেমো পেমেন্ট সম্পূর্ণ করুন",
  "Cancel Payment": "পেমেন্ট বাতিল করুন",
  "Demo payment cancelled.": "ডেমো পেমেন্ট বাতিল হয়েছে।",
  "Your appointment was not confirmed. Choose a session to try again.": "আপনার সেশন নিশ্চিত হয়নি। আবার সময় বেছে নিন।",
  "Return to bookings": "বুকিং পাতায় ফিরুন",
  "Your next conversation": "আপনার পরবর্তী সেশন",
  "Book a consultation or interview with an evaluator. All times are shown in your local timezone.": "মূল্যায়নকারীর সঙ্গে পরামর্শ বা সাক্ষাৎকার বুক করুন। সব সময় আপনার স্থানীয় সময় অনুযায়ী।",
  "Book your appointment": "আপনার সেশন বুক করুন",
  "This is a demo payment. No real payment will be made. Your place is confirmed after payment, subject to availability.": "এটি শুধুমাত্র ডেমো পেমেন্ট। কোনো আসল টাকা কাটা হবে না। পেমেন্টের পরে আসন খালি থাকলে বুকিং নিশ্চিত হবে।",
  "Purpose": "উদ্দেশ্য",
  "Consultation · পরামর্শ": "পরামর্শ",
  "Interview · সাক্ষাৎকার": "সাক্ষাৎকার",
  "Anything your evaluator should know?": "মূল্যায়নকারীকে কিছু জানাতে চান?",
  "Booking…": "বুকিং হচ্ছে…",
  "Proceed to Demo Payment": "ডেমো পেমেন্টে যান",
  "Cancel": "বাতিল করুন",
  "Available times": "খালি সময়",
  "No available times yet": "এখন কোনো সময় খালি নেই",
  "Check back when an evaluator publishes new appointment slots.": "মূল্যায়নকারী নতুন সময় প্রকাশ করলে আবার দেখুন।",
  "Until": "পর্যন্ত",
  "Closed": "বন্ধ",
  "Past slot": "সময় পেরিয়েছে",
  "Choose time": "সময় বেছে নিন",
  "Full": "আসন পূর্ণ",
  "Your bookings": "আমার বুকিং",
  "No appointments yet": "এখনো কোনো বুকিং নেই",
  "Confirmed bookings and cancellations will appear here.": "নিশ্চিত ও বাতিল বুকিং এখানে দেখাবে।",
  "Complete Payment": "পেমেন্ট সম্পূর্ণ করুন",
  "Cancel this appointment and free your place?": "এই বুকিং বাতিল করে আসন ছেড়ে দেবেন?",
  "Confirm cancellation": "বাতিল নিশ্চিত করুন",
  "Keep booking": "বুকিং রাখুন",
  "Cancel appointment": "বুকিং বাতিল করুন",
  "Appointment cancelled. You can choose a new time.": "বুকিং বাতিল হয়েছে। নতুন সময় বেছে নিতে পারেন।",
  "Booking pending payment. Use Complete Payment below to continue.": "পেমেন্ট বাকি আছে। নিচে পেমেন্ট সম্পূর্ণ করুন।",
  "Build your next opportunity": "আপনার সিভি তৈরি করুন",
  "Create a clear, professional CV. Save your changes, then preview or print your saved CV.": "পরিষ্কার ও সাজানো সিভি তৈরি করুন। সংরক্ষণ করে প্রিভিউ বা প্রিন্ট করুন।",
  "You have unsaved CV changes.": "সিভির পরিবর্তন সংরক্ষণ করা হয়নি।",
  "Keep editing": "সম্পাদনা চালিয়ে যান",
  "Discard changes and leave": "পরিবর্তন বাদ দিয়ে বের হন",
  "Edit profile, photo & skills →": "প্রোফাইল, ছবি ও দক্ষতা সম্পাদনা করুন →",
  "Profile photo required. Add a photo in My profile.": "প্রোফাইলে ছবি প্রয়োজন। আমার প্রোফাইলে ছবি যোগ করুন।",
  "Your built CV is empty. Add a summary or your first entry below, then save.": "সিভি খালি। নিচে পরিচিতি বা প্রথম তথ্য যোগ করে সংরক্ষণ করুন।",
  "Professional summary": "পেশাগত পরিচিতি",
  "Introduce your strengths and career goals": "আপনার দক্ষতা ও কাজের লক্ষ্য লিখুন",
  "LinkedIn URL": "লিংকডইন লিংক",
  "GitHub URL": "গিটহাব লিংক",
  "Your CV uses the same skills as your profile.": "প্রোফাইলে দেওয়া দক্ষতাই সিভিতে থাকবে।",
  "No skills added. Add skills from My profile.": "দক্ষতা নেই। আমার প্রোফাইল থেকে যোগ করুন।",
  "+ Add": "+ যোগ করুন",
  "No": "এখনো নেই:",
  " yet. Include what is relevant to you.": "। আপনার জন্য প্রাসঙ্গিক তথ্য যোগ করুন।",
  "Unsaved changes": "পরিবর্তন সংরক্ষণ হয়নি",
  "All changes saved": "সব পরিবর্তন সংরক্ষিত",
  "Ready to build your CV": "সিভি তৈরি শুরু করুন",
  "Preview saved CV": "সংরক্ষিত সিভি দেখুন",
  "Save CV": "সিভি সংরক্ষণ করুন",
  "CV saved. Preview shows this saved version.": "সিভি সংরক্ষিত হয়েছে। প্রিভিউতে এই তথ্য দেখাবে।",
  "CV preview": "সিভি প্রিভিউ",
  "A professional view of the saved CV. Use your browser’s print dialog to save as PDF.": "সংরক্ষিত সিভি দেখুন। ব্রাউজারের প্রিন্ট অপশন থেকে পিডিএফ সংরক্ষণ করতে পারবেন।",
  "← Edit CV": "← সিভি সম্পাদনা করুন",
  "Print / Save as PDF": "প্রিন্ট / পিডিএফ সংরক্ষণ",
  "No built CV yet": "এখনো সিভি তৈরি হয়নি",
  "Add your summary, education or experience in the CV Builder, then save.": "সিভি তৈরির পাতায় পরিচিতি, শিক্ষা বা অভিজ্ঞতা যোগ করে সংরক্ষণ করুন।",
  "Portfolio": "কাজের নমুনা",
  "LinkedIn": "লিংকডইন",
  "GitHub": "গিটহাব",
  "Present": "বর্তমান",
  "Grade / CGPA:": "ফলাফল / সিজিপিএ:",
  "Technologies:": "প্রযুক্তি:",
  "Education": "শিক্ষা",
  "Work experience": "কাজের অভিজ্ঞতা",
  "Projects": "প্রকল্প",
  "Certifications & training": "সনদ ও প্রশিক্ষণ",
  "Languages": "ভাষা",
  "Achievements & awards": "অর্জন ও পুরস্কার",
  "Start date": "শুরুর তারিখ",
  "End date": "শেষের তারিখ",
  "Description / responsibilities": "বিবরণ / দায়িত্ব",
  "Institution": "শিক্ষাপ্রতিষ্ঠান",
  "Degree / qualification": "ডিগ্রি / যোগ্যতা",
  "Field of study": "পড়াশোনার বিষয়",
  "Currently studying": "এখন পড়াশোনা করছি",
  "Grade / CGPA": "ফলাফল / সিজিপিএ",
  "Organization": "প্রতিষ্ঠান",
  "Role / title": "পদবি",
  "Currently working": "এখন কাজ করছি",
  "Project name": "প্রকল্পের নাম",
  "Technologies": "প্রযুক্তি",
  "Project URL": "প্রকল্পের লিংক",
  "Repository URL": "কোডের লিংক",
  "Certification / course": "সনদ / কোর্স",
  "Issuing organization": "সনদদাতা প্রতিষ্ঠান",
  "Issue date": "প্রদানের তারিখ",
  "Credential URL": "সনদের লিংক",
  "Language": "ভাষা",
  "Proficiency": "দক্ষতার স্তর",
  "Title": "শিরোনাম",
  "Issuer / organization": "প্রদানকারী / প্রতিষ্ঠান",
  "Award date": "পুরস্কারের তারিখ",
  "Upload Photo": "ছবি আপলোড করুন",
  "Change Photo": "ছবি বদলান",
  "Save photo": "ছবি সংরক্ষণ করুন",
  "Selected photo preview": "বেছে নেওয়া ছবির প্রিভিউ",
  "Choose a JPEG or PNG up to 5 MB.": "সর্বোচ্চ ৫ এমবির জেপিজি বা পিএনজি ছবি বেছে নিন।",
  "JPEG or PNG, up to 5 MB and 16 megapixels. This photo is visible on your profile and applications.": "জেপিজি বা পিএনজি, সর্বোচ্চ ৫ এমবি ও ১৬ মেগাপিক্সেল। ছবিটি প্রোফাইল ও আবেদনে দেখা যাবে।",
  "Your profile photo has been saved.": "প্রোফাইলের ছবি সংরক্ষিত হয়েছে।",
  "Job assessment": "চাকরির মূল্যায়ন",
  "A job-specific interview. Answer in your own words; typing is always available.": "কাজ অনুযায়ী সাক্ষাৎকার। নিজের ভাষায় উত্তর দিন; সব সময় লিখে উত্তর দিতে পারবেন।",
  "← My applications": "← আমার আবেদন",
  "answers": "উত্তর",
  "Assessment progress": "মূল্যায়নের অগ্রগতি",
  "Assessment completed. Your responses have been submitted for this application.": "মূল্যায়ন সম্পূর্ণ। এই আবেদনের জন্য উত্তর জমা হয়েছে।",
  "Your interview is submitted. Evaluation could not finish; the employer can review its status. Answers are now locked.": "সাক্ষাৎকার জমা হয়েছে। মূল্যায়ন শেষ করা যায়নি; নিয়োগকর্তা অবস্থা দেখতে পারবেন। উত্তর এখন বদলানো যাবে না।",
  "This application is not currently eligible for an assessment.": "এই আবেদনে এখন মূল্যায়ন দেওয়া যাবে না।",
  "One interview per application, with up to": "প্রতি আবেদনে একটি সাক্ষাৎকার, সর্বোচ্চ",
  "answers. You can return to this page to continue your saved conversation.": "টি উত্তর। পরে এই পাতায় ফিরে কথোপকথন চালিয়ে যেতে পারবেন।",
  "Starting…": "শুরু হচ্ছে…",
  "Your conversation will appear here": "কথোপকথন এখানে দেখাবে",
  "The first question appears when the interview service starts your assessment.": "সাক্ষাৎকার সেবা মূল্যায়ন শুরু করলে প্রথম প্রশ্ন দেখা যাবে।",
  "Voice input language": "কথা বলে লেখার ভাষা",
  "Your answer": "আপনার উত্তর",
  "Review before sending. Submitted answers cannot be edited.": "পাঠানোর আগে দেখে নিন। জমা দেওয়া উত্তর বদলানো যাবে না।",
  "Processing answer…": "উত্তর যাচাই হচ্ছে…",
  "Send answer": "উত্তর পাঠান",
  "Refresh conversation": "কথোপকথন হালনাগাদ করুন",
  "Assessment conversation": "মূল্যায়নের কথোপকথন",
  "AI interviewer": "এআই সাক্ষাৎকার সহকারী",
  "Candidate": "প্রার্থী",
  "Message": "বার্তা",
  " Your latest answer was not submitted; you can edit it and retry.": " শেষ উত্তর জমা হয়নি; সম্পাদনা করে আবার পাঠান।",
  " Refresh the conversation before trying again. Your typed answer is retained.": " আবার চেষ্টা করার আগে কথোপকথন হালনাগাদ করুন। লেখা উত্তর রাখা হয়েছে।",
  "Dictate your answer": "কথা বলে উত্তর লিখুন",
  "Speak your answer, review the transcript, then use the text in your answer below.": "উত্তর বলুন, লেখা দেখে নিন, তারপর নিচের উত্তরে যোগ করুন।",
  "Use this text in my answer": "উত্তরে লেখাটি যোগ করুন",
  "Optional voice input": "ঐচ্ছিক ভয়েস ইনপুট",
  "Onboarding progress": "পরিচিতি তৈরির অগ্রগতি",
  "Show what you know": "আপনার দক্ষতা দেখান",
  "Choose an assessment for your track. Save your progress, submit your answers and receive personal evaluator feedback.": "আপনার পেশার মূল্যায়ন বেছে নিন। অগ্রগতি সংরক্ষণ করুন, উত্তর জমা দিন ও মূল্যায়নকারীর মতামত পান।",
  "In progress": "চলছে",
  "Awaiting review": "যাচাইয়ের অপেক্ষায়",
  "Results released": "ফল প্রকাশিত",
  "No assessments available yet": "এখনো মূল্যায়ন নেই",
  "Your track’s assessments will appear here when published.": "আপনার পেশার মূল্যায়ন প্রকাশ হলে এখানে দেখাবে।",
  "Ready to start": "শুরু করতে প্রস্তুত",
  "questions · Untimed ·": "টি প্রশ্ন · সময়সীমা নেই ·",
  "Your responses guide a practical skills conversation with an evaluator.": "আপনার উত্তর ধরে মূল্যায়নকারী ব্যবহারিক দক্ষতা নিয়ে কথা বলবেন।",
  "Opening…": "খোলা হচ্ছে…",
  "Start assessment →": "মূল্যায়ন শুরু করুন →",
  "Continue assessment →": "মূল্যায়ন চালিয়ে যান →",
  "View result →": "ফল দেখুন →",
  "View submission →": "জমা দেওয়া উত্তর দেখুন →",
  "Your assessment": "আপনার মূল্যায়ন",
  "Take your time. Save answers before leaving; submitted answers are final.": "সময় নিয়ে উত্তর দিন। বের হওয়ার আগে সংরক্ষণ করুন; জমা দিলে আর বদলানো যাবে না।",
  "Progress saved. You can return to this assessment later.": "অগ্রগতি সংরক্ষিত হয়েছে। পরে আবার ফিরে আসতে পারবেন।",
  "answered": "উত্তর দেওয়া হয়েছে",
  "Submitted. Your evaluator takes it from here.": "জমা হয়েছে। এবার মূল্যায়নকারী দেখবেন।",
  "Your answers are saved and locked. Your score and feedback appear here after the evaluator releases them.": "উত্তর সংরক্ষিত হয়েছে এবং আর বদলানো যাবে না। মূল্যায়নকারী প্রকাশ করলে ফল ও মতামত দেখবেন।",
  "Book a conversation →": "কথা বলার সময় বুক করুন →",
  "Question": "প্রশ্ন",
  "← Previous": "← আগের প্রশ্ন",
  "Next question →": "পরের প্রশ্ন →",
  "Submit all": "সব উত্তর জমা দিন:",
  "answers?": "টি উত্তর?",
  "This saves your latest choices and locks the attempt for review. You cannot change your answers afterwards.": "সর্বশেষ উত্তর সংরক্ষণ করে যাচাইয়ের জন্য জমা হবে। পরে আর উত্তর বদলাতে পারবেন না।",
  "Submitting…": "জমা হচ্ছে…",
  "Confirm submission": "জমা নিশ্চিত করুন",
  "Keep reviewing": "আরেকবার দেখুন",
  "Your progress": "আপনার অগ্রগতি",
  "You have unsaved changes.": "পরিবর্তন সংরক্ষণ হয়নি।",
  "All current choices are saved.": "সব উত্তর সংরক্ষিত আছে।",
  "Save progress": "অগ্রগতি সংরক্ষণ করুন",
  "Review & submit": "দেখে জমা দিন",
  "Answer every question to submit.": "জমা দিতে সব প্রশ্নের উত্তর দিন।",
  "Back to assessments": "মূল্যায়নের তালিকায় ফিরুন",
  "Released result": "প্রকাশিত ফল",
  "Discuss your next steps →": "পরবর্তী ধাপ নিয়ে কথা বলুন →",
  "Complete": "সম্পূর্ণ",
  "Incomplete": "অসম্পূর্ণ",
  "Managed placements": "আমার নিয়োগ",
  "A clear view of every working relationship, its coverage and its next step.": "নিয়োগের অবস্থা, সুরক্ষা ও পরবর্তী ধাপ দেখুন।",
  "Replacement requests": "বিকল্প কর্মীর অনুরোধ",
  "Replacements on time": "সময়মতো বিকল্প কর্মী",
  "Your next placement starts here": "আপনার নিয়োগ এখানে দেখাবে",
  "Complete your profile and assessments. Your managed placements will appear here.": "প্রোফাইল ও মূল্যায়ন সম্পূর্ণ করুন। নিয়োগ হলে এখানে দেখাবে।",
  "Placement #": "নিয়োগ #",
  "· Started": "· শুরু",
  "30-day managed TRADE coverage": "ট্রেড নিয়োগে ৩০ দিনের সুরক্ষা",
  "Expires": "মেয়াদ শেষ",
  "The guarantee window has ended.": "সুরক্ষার মেয়াদ শেষ হয়েছে।",
  "Standard placement · no replacement guarantee": "সাধারণ নিয়োগ · বিকল্প কর্মীর নিশ্চয়তা নেই",
  "View replacement timelines →": "বিকল্প কর্মীর অগ্রগতি দেখুন →",
  "Continuity, with a clear timeline": "বিকল্প কর্মীর অগ্রগতি",
  "Follow every replacement from request to activation. Eligible workers are selected by queue join time, with a stable ID tie-breaker.": "অনুরোধ থেকে নিয়োগ পর্যন্ত অগ্রগতি দেখুন। যোগ্য কর্মীদের তালিকায় যোগ দেওয়ার সময় অনুযায়ী বাছাই করা হয়; একই সময় হলে আইডির ক্রম ধরা হয়।",
  "Refresh status": "অবস্থা হালনাগাদ করুন",
  "View placements": "নিয়োগ দেখুন",
  "No replacement requests yet": "এখনো বিকল্প কর্মীর অনুরোধ নেই",
  "Requests and their 24-hour timelines will appear here.": "অনুরোধ ও তার ২৪ ঘণ্টার অগ্রগতি এখানে দেখাবে।",
  "Replacement #": "বিকল্প কর্মীর অনুরোধ #",
  "· Placement #": "· নিয়োগ #",
  "continuity": "কাজ চালিয়ে যাওয়া",
  "· Replacing": "· পরিবর্তে",
  "24-hour operational target": "২৪ ঘণ্টার মধ্যে কাজের লক্ষ্য",
  "24-hour target elapsed": "২৪ ঘণ্টার লক্ষ্যের অগ্রগতি",
  "Delivered on time": "সময়মতো সম্পূর্ণ",
  "Completed after target": "লক্ষ্য সময়ের পরে সম্পূর্ণ",
  "Target exceeded": "লক্ষ্য সময় পেরিয়েছে",
  "Started": "শুরু",
  ". Retrying keeps this original deadline.": "। আবার চেষ্টা করলেও এই সময়সীমা থাকবে।",
  "Request received": "অনুরোধ এসেছে",
  "Matching queue": "তালিকা থেকে খোঁজা হচ্ছে",
  "Candidate selected": "প্রার্থী বেছে নেওয়া হয়েছে",
  "Accepted": "সম্মতি হয়েছে",
  "Replacement active": "বিকল্প কর্মী নিয়োগ হয়েছে",
  "Replacement progress": "বিকল্প কর্মীর অগ্রগতি",
  "Needs attention": "মনোযোগ প্রয়োজন",
  "Current step": "বর্তমান ধাপ",
  "Replacement worker": "বিকল্প কর্মী",
  "Selected from the eligible FIFO queue": "যোগ্য কর্মীদের তালিকা থেকে ক্রম অনুযায়ী বাছাই",
  "Location not provided": "এলাকা দেওয়া নেই",
  "is active. The original placement is marked replaced.": "সক্রিয়। আগের নিয়োগ পরিবর্তিত হয়েছে।",
  "Eligible TRADE workers join by skill. Position follows join time, not assessment score; currently ineligible workers are skipped during matching.": "যোগ্য ট্রেড কর্মীরা দক্ষতা অনুযায়ী যোগ দেন। তালিকার অবস্থান যোগ দেওয়ার সময় অনুযায়ী; মূল্যায়নের নম্বর অনুযায়ী নয়। এখন যোগ্য নন এমন কর্মী বাছাইয়ে বাদ পড়েন।",
  "Choose a profile skill": "প্রোফাইলের দক্ষতা বেছে নিন",
  "Update skills & availability": "দক্ষতা ও প্রস্তুতি হালনাগাদ করুন",
  "Ready for your first queue?": "প্রথম তালিকায় যোগ দিতে প্রস্তুত?",
  "Complete the readiness checks above, then select a skill to join.": "উপরের প্রস্তুতির ধাপ পূরণ করে দক্ষতা বেছে যোগ দিন।",
  "Reserved": "সংরক্ষিত",
  "Exited": "বের হয়ে গেছেন",
  "Joined": "যোগ দিয়েছেন",
  "An employer is confirming your placement. View your replacement timeline for updates.": "নিয়োগকর্তা আপনার নিয়োগ নিশ্চিত করছেন। বিকল্প কর্মীর অগ্রগতি পাতায় খবর দেখুন।",
  "Ready for matching when all eligibility checks pass.": "সব যোগ্যতার শর্ত পূরণ হলে বাছাইয়ের জন্য প্রস্তুত।",
  "Leave queue": "তালিকা ছাড়ুন",
  "View selection": "বাছাইয়ের অবস্থা দেখুন",
  "You left this queue.": "আপনি এই তালিকা ছেড়েছেন।",
  "Career, training and account updates, delivered inside your workspace.": "কাজ, প্রশিক্ষণ ও অ্যাকাউন্টের খবর এখানে দেখুন।",
  "unread updates": "টি না-পড়া খবর",
  "Mark all as read": "সব পড়া হয়েছে করুন",
  "You’re all caught up": "সব খবর দেখা হয়েছে",
  "New career, training and account activity will appear here.": "কাজ, প্রশিক্ষণ ও অ্যাকাউন্টের নতুন খবর এখানে দেখাবে।",
  "Unread": "পড়া হয়নি",
  "Mark read": "পড়া হয়েছে",
  "View activity →": "বিস্তারিত দেখুন →",
  "Explore practical learning pathways. A referral gives you a next step to discuss with your evaluator; it does not automatically enroll you.": "ব্যবহারিক প্রশিক্ষণ দেখুন। পরামর্শ পেলে মূল্যায়নকারীর সঙ্গে পরবর্তী ধাপ নিয়ে কথা বলুন; এতে নিজে থেকে ভর্তি হয় না।",
  "Referred": "পরামর্শের তারিখ",
  "Your next chapter starts here": "আপনার শেখার পরবর্তী ধাপ",
  "No referrals yet. Your evaluator can recommend a program after reviewing your assessment.": "এখনো প্রশিক্ষণের পরামর্শ নেই। মূল্যায়ন দেখে মূল্যায়নকারী পরামর্শ দিতে পারবেন।",
  "Learning catalog": "প্রশিক্ষণের তালিকা",
  "FOUNDATION SKILLS": "মৌলিক দক্ষতা",
  "New programs are on the way": "নতুন প্রশিক্ষণ আসছে",
  "Check back with your evaluator for learning options.": "প্রশিক্ষণের সুযোগ জানতে মূল্যায়নকারীর সঙ্গে কথা বলুন।",
  "My referrals · আমার প্রশিক্ষণ": "আমার প্রশিক্ষণের পরামর্শ",
  "Profile photo required · ছবি যোগ করুন। Complete your profile by uploading your photo.": "ছবি যোগ করুন।",
  "Profile photo · প্রোফাইল ছবি": "প্রোফাইলের ছবি",
  "Skills · দক্ষতা": "দক্ষতা",
  "TRADE · দক্ষ কর্মী": "দক্ষ কর্মী",
  "TRADE · দক্ষতার পথে": "দক্ষতার পথে",
  "অভিজ্ঞতা · Experience": "অভিজ্ঞতা",
  "অভিজ্ঞতা লিখুন · Type your experience": "অভিজ্ঞতা লিখুন",
  "অভিজ্ঞতায় যোগ করুন · Use this text": "অভিজ্ঞতায় যোগ করুন",
  "আপনার কাজের অভিজ্ঞতা বলুন, তারপর লেখাটি দেখে যোগ করুন। Describe your experience, then review the text.": "আপনার কাজের অভিজ্ঞতা বলুন, তারপর লেখাটি দেখে যোগ করুন।",
  "আপনার দক্ষতা যোগ করুন এবং কাজের প্রস্তুতি জানান। Add your trade and experience so employers can find you.": "আপনার দক্ষতা যোগ করুন এবং কাজের প্রস্তুতি জানান।",
  "আপনার পরিচিতি · Your profile": "আপনার পরিচিতি",
  "আমরা অডিও সংরক্ষণ করি না। ব্রাউজার ভয়েস প্রক্রিয়ার জন্য অডিও পাঠাতে পারে। We do not store audio; your browser may process it online.": "আমরা অডিও সংরক্ষণ করি না। ব্রাউজার ভয়েস প্রক্রিয়ার জন্য অডিও পাঠাতে পারে।",
  "আরও কিছু ধাপ বাকি · A few steps to go": "আরও কিছু ধাপ বাকি",
  "এই ব্রাউজারে ভয়েস চালু নেই। নিচে লিখে সম্পূর্ণ করতে পারবেন। Voice is unavailable; type below to continue.": "এই ব্রাউজারে ভয়েস চালু নেই। নিচে লিখে সম্পূর্ণ করতে পারবেন।",
  "একটি প্রধান দক্ষতা বেছে নিন। Choose your main skill; add more later.": "একটি প্রধান দক্ষতা বেছে নিন।",
  "এখন প্রস্তুত নই · Unavailable": "এখন প্রস্তুত নই",
  "এটি আপনার নিজের দেওয়া পরিচিতি। যাচাই ও মূল্যায়ন প্ল্যাটফর্ম আলাদাভাবে সম্পন্ন করবে। Platform verification and assessment are separate steps.": "এটি আপনার নিজের দেওয়া পরিচিতি। যাচাই ও মূল্যায়ন প্ল্যাটফর্ম আলাদাভাবে সম্পন্ন করবে।",
  "এবার প্ল্যাটফর্ম যাচাইয়ের তথ্য জমা দিন এবং মূল্যায়ন সম্পূর্ণ করুন। Complete verification and assessment to build your readiness.": "এবার প্ল্যাটফর্ম যাচাইয়ের তথ্য জমা দিন এবং মূল্যায়ন সম্পূর্ণ করুন।",
  "এলাকা · Location": "এলাকা",
  "ঐচ্ছিক · Optional": "ঐচ্ছিক",
  "কথা বলুন · Start microphone": "কথা বলুন",
  "কাজের অপেক্ষার তালিকা · Your place in line": "কাজের অপেক্ষার তালিকা",
  "কাজের জন্য প্রস্তুত? · Availability": "কাজের জন্য প্রস্তুত?",
  "কাজের প্রস্তুতি · Readiness": "কাজের প্রস্তুতি",
  "কোনো পেশা পাওয়া যায়নি। পরে আবার চেষ্টা করুন। No active trade skills available.": "কোনো পেশা পাওয়া যায়নি। পরে আবার চেষ্টা করুন।",
  "ড্যাশবোর্ড · Dashboard": "ড্যাশবোর্ড",
  "তালিকায় যোগ দিন · Join queue": "তালিকায় যোগ দিন",
  "তিনটি সহজ ধাপে পরিচিতি তৈরি করুন। Build your work profile in three simple steps.": "তিনটি সহজ ধাপে পরিচিতি তৈরি করুন।",
  "দক্ষতা বেছে নিন · Choose your skill": "দক্ষতা বেছে নিন",
  "দেখে নিশ্চিত করুন · Review your details": "দেখে নিশ্চিত করুন",
  "নাম · Name": "নাম",
  "নিজে লিখুন · You can always type in the field below.": "নিজে লিখুন",
  "নিশ্চিত · Confirm": "নিশ্চিত",
  "পরবর্তী · Continue →": "পরবর্তী→",
  "পরিচিতি · Profile": "পরিচিতি",
  "পরিচিতি সংরক্ষিত হয়েছে। Your profile is saved.": "পরিচিতি সংরক্ষিত হয়েছে।",
  "পর্যালোচনা · Manual evaluator review": "পর্যালোচনা",
  "পুরো নাম · Full name": "পুরো নাম",
  "পেশা · Primary trade": "পেশা",
  "পেশা · Trade": "পেশা",
  "প্রশিক্ষণ · Your next step": "প্রশিক্ষণ",
  "প্রস্তুত · Available": "প্রস্তুত",
  "প্রস্তুতি · Availability": "প্রস্তুতি",
  "প্রস্তুতির অবস্থা বর্তমান তথ্য অনুযায়ী। এটি অপেক্ষমাণ তালিকায় ভর্তি বা চাকরির নিশ্চয়তা নয়। Readiness is based on current records; it does not confirm queue admission or a job.": "প্রস্তুতির অবস্থা বর্তমান তথ্য অনুযায়ী। এটি অপেক্ষমাণ তালিকায় ভর্তি বা চাকরির নিশ্চয়তা নয়।",
  "ফোন · Phone": "ফোন",
  "ফোন · Phone (01…)": "ফোন",
  "বাংলা · Bangla": "বাংলা",
  "বাংলায় বলুন · Speak in Bangla": "বাংলায় বলুন",
  "বাংলায় শুরু করুন · Voice-assisted onboarding →": "বাংলায় শুরু করুন→",
  "ভয়েস কাজ করছে না। আবার চেষ্টা করুন অথবা লিখুন। Voice input failed.": "ভয়েস কাজ করছে না। আবার চেষ্টা করুন অথবা লিখুন।",
  "ভয়েস চালু হয়নি। লিখে এগিয়ে যান। Could not start voice input.": "ভয়েস চালু হয়নি। লিখে এগিয়ে যান।",
  "যাচাই · Account verification": "যাচাই",
  "যাচাই শুরু করুন · Start verification →": "যাচাই শুরু করুন→",
  "শুনছি… থামুন · Stop listening": "শুনছি… থামুন",
  "শুনছি… ধীরে ও স্পষ্ট করে বলুন। Listening…": "শুনছি… ধীরে ও স্পষ্ট করে বলুন।",
  "শুনে লেখা · Edit transcript": "শুনে লেখা",
  "সংরক্ষণ করুন · Save profile": "সংরক্ষণ করুন",
  "সফলভাবে তালিকায় যোগ হয়েছে · You joined the queue.": "সফলভাবে তালিকায় যোগ হয়েছে",
  "হালনাগাদ · Refresh": "হালনাগাদ",
  "হ্যাঁ, কাজ করতে প্রস্তুত · Available": "হ্যাঁ, কাজ করতে প্রস্তুত",
  "← পেছনে · Back": "← পেছনে",
  "✓ যোগ্যতার শর্ত পূরণ হয়েছে · Readiness requirements met": "✓ যোগ্যতার শর্ত পূরণ হয়েছে",
  "Welcome": "স্বাগতম",
  "TRADE": "দক্ষ কর্মী",
  "TECH": "পেশাজীবী",
  "Familiar": "প্রাথমিক ধারণা",
  "Practising": "চর্চা করছেন",
  "Experienced": "অভিজ্ঞ",
  "education": "শিক্ষা",
  "experience": "অভিজ্ঞতা",
  "project": "প্রকল্প",
  "certification": "সনদ",
  "language": "ভাষা",
  "achievement": "অর্জন",
  "Move entry": "তথ্যের ক্রম বদলান",
  "Remove this entry? Save CV to confirm the removal.": "এই তথ্য সরাবেন? নিশ্চিত করতে সিভি সংরক্ষণ করুন।",
  "places available": "টি আসন খালি",
  "hours": "ঘণ্টা",
  "minutes remaining": "মিনিট বাকি",
  "Due": "লক্ষ্য সময়",
  "Enter a valid number of months.": "সঠিক মাসের সংখ্যা লিখুন।",
  "No experience required": "অভিজ্ঞতা প্রয়োজন নেই",
  "Not started": "শুরু হয়নি",
  "Completed": "সম্পূর্ণ",
  "Evaluation failed": "মূল্যায়ন করা যায়নি",
  "Approved": "অনুমোদিত",
  "Rejected": "বাতিল",
  "In review": "যাচাই চলছে",
  "Pending": "অপেক্ষমাণ",
  "Not submitted": "জমা দেওয়া হয়নি",
  "available": "কাজ করতে প্রস্তুত",
  "unavailable": "এখন প্রস্তুত নন",
  "applied": "আবেদন করা হয়েছে",
  "shortlisted": "প্রাথমিকভাবে বাছাই হয়েছে",
  "rejected": "বাতিল",
  "withdrawn": "প্রত্যাহার করা হয়েছে",
  "hired": "নিয়োগ হয়েছে",
  "active": "সক্রিয়",
  "closed": "বন্ধ",
  "verified": "যাচাইকৃত",
  "not submitted": "জমা দেওয়া হয়নি",
  "pending": "অপেক্ষমাণ",
  "in review": "যাচাই চলছে",
  "failed": "ব্যর্থ",
  "flagged": "পুনরায় যাচাই প্রয়োজন",
  "in progress": "চলছে",
  "submitted": "জমা হয়েছে",
  "completed": "সম্পূর্ণ",
  "pending payment": "পেমেন্ট বাকি",
  "booked": "বুকিং নিশ্চিত",
  "cancelled": "বাতিল",
  "success": "সফল",
  "consultation": "পরামর্শ",
  "interview": "সাক্ষাৎকার",
  "session booking": "সেশন বুকিং",
  "booking": "সেশন বুকিং",
  "hire ready": "কাজের জন্য প্রস্তুত",
  "needs training": "প্রশিক্ষণ প্রয়োজন",
  "not ready": "এখনো প্রস্তুত নন",
  "queued": "অপেক্ষার তালিকায়",
  "reserved": "সংরক্ষিত",
  "exited": "তালিকা ছেড়েছেন",
  "on time": "সময়মতো",
  "breached": "সময় পেরিয়েছে",
  "terminated": "শেষ করা হয়েছে",
  "replaced": "বিকল্প কর্মী নিয়োগ হয়েছে",
  "candidate selected": "প্রার্থী বাছাই হয়েছে",
  "accepted": "সম্মতি হয়েছে",
  "requested": "অনুরোধ করা হয়েছে",
  "matching": "খোঁজা হচ্ছে",
  "referred": "প্রশিক্ষণের পরামর্শ দেওয়া হয়েছে",
  "The AI interview provider is not configured yet. Please return when the service is available.": "AI সাক্ষাৎকার সেবা এখনো কনফিগার করা হয়নি। সেবা চালু হলে আবার চেষ্টা করুন।",
  "The interview service returned an unusable response. Please contact the platform team.": "সাক্ষাৎকার সেবার উত্তর ব্যবহার করা যায়নি। প্ল্যাটফর্মের সঙ্গে যোগাযোগ করুন।",
  "The interview service is temporarily unavailable. Your saved conversation is safe.": "সাক্ষাৎকার সেবা এখন চালু নেই। সংরক্ষিত কথোপকথন ঠিক আছে।",
  ", answered": ", উত্তর দেওয়া হয়েছে",
  ", unanswered": ", উত্তর বাকি",
  "TRADE পরিচিতি · Trade track": "ট্রেড পরিচিতি",
  "সক্রিয় অ্যাকাউন্ট · Active account": "সক্রিয় অ্যাকাউন্ট",
  "প্ল্যাটফর্ম যাচাই · Platform verified": "প্ল্যাটফর্ম যাচাই",
  "পেশা ও দক্ষতা · Trade & skill": "পেশা ও দক্ষতা",
  "মূল্যায়নে প্রস্তুত · Hire-ready assessment": "মূল্যায়নে প্রস্তুত",
  "কাজের জন্য প্রস্তুত · Available": "কাজের জন্য প্রস্তুত",
  "অন্য কাজে সংরক্ষিত নন · Not reserved": "অন্য কাজে সংরক্ষিত নন",
  "চলমান নিয়োগ নেই · No active placement": "চলমান নিয়োগ নেই",
  "National ID": "জাতীয় পরিচয়পত্র",
  "Upload a clear PDF, JPG or PNG copy, up to 5 MB. Platform/manual verification.": "সর্বোচ্চ ৫ এমবির পরিষ্কার পিডিএফ, জেপিজি বা পিএনজি কপি দিন। প্ল্যাটফর্ম ম্যানুয়ালি যাচাই করবে।",
  "contacted": "যোগাযোগ করা হয়েছে",
  "enrolled": "ভর্তি হয়েছেন",
  "Profile photo": "প্রোফাইলের ছবি",
  "No profile photo": "প্রোফাইলের ছবি নেই",
  "to find a role and apply.": "পছন্দের কাজ খুঁজে আবেদন করুন।",
  "yet. Include what is relevant to you.": "নেই। আপনার জন্য প্রাসঙ্গিক তথ্য যোগ করুন।",
  "· Score": "· নম্বর",
  "Placement active": "নিয়োগ শুরু হয়েছে",
  "Placement ended": "নিয়োগ শেষ হয়েছে",
  "Replacement requested": "বিকল্প কর্মীর অনুরোধ হয়েছে",
  "Replacement confirmed": "বিকল্প কর্মী নিশ্চিত হয়েছে",
  "Replacement cancelled": "বিকল্প কর্মীর অনুরোধ বাতিল",
  "A replacement candidate is ready": "একজন বিকল্প কর্মী প্রস্তুত",
  "Replacement needs attention": "বিকল্প কর্মীর অনুরোধে মনোযোগ প্রয়োজন",
  "Your next learning step": "আপনার শেখার পরবর্তী ধাপ",
  "Account status updated": "অ্যাকাউন্টের অবস্থা বদলেছে",
  "Candidate withdrew": "প্রার্থী তালিকা ছেড়েছেন",
  "Placement activated": "নিয়োগ শুরু হয়েছে",
  "No longer eligible after reservation release": "সংরক্ষণ ছাড়ার পরে যোগ্যতার শর্ত পূরণ হয়নি",
  "No eligible candidates are currently available in this skill queue.": "এই দক্ষতার তালিকায় এখন কোনো যোগ্য প্রার্থী নেই।",
  "Employer cancelled the request.": "নিয়োগকর্তা অনুরোধ বাতিল করেছেন।",
  "suspended": "সাময়িকভাবে বন্ধ",
  "inactive": "নিষ্ক্রিয়"
}
