import { useCallback, useState } from 'react'
import { Link, useParams } from 'react-router'
import { useAuth } from '../auth/useAuth'
import { Workspace, LoadState, Field, Feedback, Empty } from '../marketplace/shared'
import { useLoad } from '../marketplace/useLoad'
import { apiFailure } from '../../services/api'
import { tradeApi, statusLabels, statusClass, type VerificationReview, type VerificationStatus } from './api'
import { ReadinessCard } from './ReadinessCard'
const date = (value: string) => new Date(value).toLocaleString()
export function VerificationPage() {
  const state = useLoad(tradeApi.history), { user } = useAuth()
  const [reference, setReference] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState(''), [success, setSuccess] = useState('')
  const latest = state.data?.[0], maySubmit = !latest || ['FAILED', 'FLAGGED'].includes(latest.status)
  async function submit() { setBusy(true); setError(''); setSuccess(''); try { await tradeApi.submit(reference); setReference(''); setSuccess('তথ্য জমা হয়েছে। Submitted for platform review.'); state.reload() } catch (e) { setError(apiFailure(e).message) } finally { setBusy(false) } }
  return <Workspace title="যাচাই ও আস্থা · Verification" subtitle="প্ল্যাটফর্মের কর্মী আপনার তথ্য যাচাই করবেন। This is manual platform verification, with no government NID integration."><LoadState {...state} /><Feedback error={error} success={success} />{!state.loading && !state.error && state.data && <><div className="mb-6 grid items-start gap-6 lg:grid-cols-2"><section className="surface"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-bold">আপনার অবস্থা · Your status</h2><button className="button-secondary" onClick={state.reload}>Refresh</button></div>{latest ? <><p className={`my-5 rounded-xl p-4 font-semibold ${statusClass(latest.status)}`}>{statusLabels[latest.status]}</p><p className="text-sm leading-relaxed text-slate-600">{latest.status === 'VERIFIED' ? 'আপনার তথ্য প্ল্যাটফর্মে যাচাই হয়েছে। মূল্যায়ন ও কাজের প্রস্তুতিও সম্পূর্ণ করুন। Your platform verification is complete.' : latest.status === 'FAILED' ? 'তথ্য যাচাই করা যায়নি। সঠিক তথ্য দিয়ে আবার জমা দিন। Correct your information and submit again.' : latest.status === 'FLAGGED' ? 'আরও তথ্য যাচাই প্রয়োজন। এটি অপরাধের অভিযোগ নয়। তথ্য সংশোধন করে আবার জমা দিতে পারেন। Further review is needed; this is not an accusation.' : 'আপনার তথ্য পর্যালোচনার অপেক্ষায় আছে। পরে অবস্থা হালনাগাদ করুন। Your information is awaiting review.'}</p></> : <p className="my-5 text-slate-600">এখনও তথ্য জমা হয়নি। Submit your first verification below.</p>}
    {maySubmit && <form className="mt-5 space-y-4" onSubmit={e => { e.preventDefault(); void submit() }}><fieldset disabled={busy} className="space-y-4"><Field name="identityReference" label="পরিচয় তথ্য / রেফারেন্স · Identity reference" required maxLength={255} value={reference} onChange={setReference} /><p className="text-sm leading-relaxed text-slate-500">শুধু অনুমোদিত মূল্যায়নকারী এই তথ্য দেখবেন। প্রদর্শনীর জন্য কাল্পনিক রেফারেন্স ব্যবহার করুন, যেমন DEMO-TRADE-001। Only evaluators see this reference. Use fictional information for the showcase.</p><button disabled={busy || !reference.trim()} className="button-primary w-full">{busy ? 'জমা হচ্ছে…' : 'যাচাইয়ের জন্য জমা দিন · Submit'}</button></fieldset></form>}</section>
    <section className="surface"><h2 className="text-xl font-bold">যাচাইয়ের ধাপ · Timeline</h2>{!state.data.length ? <ol className="mt-5 space-y-5 text-sm text-slate-600"><li>① পরিচয় তথ্য জমা দিন · Submit information</li><li>② মূল্যায়নকারী যাচাই করবেন · Platform review</li><li>③ সিদ্ধান্ত দেখুন · View decision</li></ol> : <ol className="mt-5 space-y-6 border-l-2 border-teal-100 pl-5">{state.data.map(v => <li key={v.id}><span className={`inline-block rounded-full px-3 py-2 text-sm font-semibold ${statusClass(v.status)}`}>{statusLabels[v.status]}</span><p className="mt-2 text-sm text-slate-600">জমা · {date(v.submittedAt)}</p>{v.reviewedAt && <p className="mt-1 text-sm text-slate-600">সিদ্ধান্ত · {date(v.reviewedAt)}</p>}</li>)}</ol>}</section></div>{user?.candidateType === 'TRADE' && <ReadinessCard key={latest ? `${latest.id}-${latest.status}` : 'new'} />}</>}</Workspace>
}
export function VerificationQueuePage() {
  const state = useLoad(tradeApi.pending)
  return <Workspace title="Verification work queue" subtitle="Review private identity references and record a careful platform decision."><LoadState {...state} />{!state.loading && !state.error && state.data && <section className="surface"><div className="mb-5 flex items-center justify-between gap-3"><h2 className="text-xl font-bold">Awaiting review · {state.data.length}</h2><button className="button-secondary" onClick={state.reload}>Refresh</button></div>{!state.data.length ? <Empty title="All caught up">New verification submissions will appear here.</Empty> : <ul className="divide-y divide-slate-100">{state.data.map(v => <li key={v.id} className="flex flex-wrap items-center justify-between gap-4 py-5"><div><p className="font-bold">{v.candidateName}</p><p className="mt-2 text-sm text-slate-500">{v.candidateType} · {v.trade || 'General verification'} · {date(v.submittedAt)}</p><span className={`mt-2 inline-block rounded-full px-3 py-1 text-sm ${statusClass(v.status)}`}>{statusLabels[v.status]}</span></div><Link className="button-secondary" to={`/evaluator/verifications/${v.id}`}>Review →</Link></li>)}</ul>}</section>}</Workspace>
}
export function VerificationReviewPage() {
  const { id } = useParams(), loader = useCallback(() => tradeApi.detail(Number(id)), [id]), state = useLoad(loader)
  return <Workspace title="Review verification" subtitle="Identity references and review notes are restricted to evaluators. Employers receive only a safe status."><LoadState {...state} />{!state.loading && !state.error && state.data && <Review initial={state.data} key={state.data.id} />}</Workspace>
}
function Review({ initial }: { initial: VerificationReview }) {
  const [v, setV] = useState(initial), [decision, setDecision] = useState<VerificationStatus>('VERIFIED'), [notes, setNotes] = useState(''), [confirm, setConfirm] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState('')
  const pending = ['PENDING', 'IN_REVIEW'].includes(v.status)
  async function submit() { setBusy(true); setError(''); try { setV(await tradeApi.review(v.id, decision, notes)); setConfirm(false) } catch (e) { setError(apiFailure(e).message) } finally { setBusy(false) } }
  return <><Feedback error={error} /><div className="grid items-start gap-6 lg:grid-cols-2"><section className="surface space-y-5"><span className="badge">Private platform review</span><h2 className="text-2xl font-bold">{v.candidateName}</h2><p className="text-slate-600">{v.candidateType} · {v.trade || 'General'} · {v.location || 'Location not provided'}</p><div className="rounded-xl bg-slate-50 p-5"><h3 className="text-sm font-semibold text-slate-500">Identity reference</h3><p className="mt-2 whitespace-pre-wrap break-words font-semibold">{v.identityReference}</p></div><p className="text-sm text-slate-500">Submitted {date(v.submittedAt)}</p><p className="text-sm leading-relaxed text-slate-600">This is manual platform verification. Check the reference through your platform process before recording a decision. Flagged means more review is needed, not criminal guilt.</p></section><form className="surface space-y-5" onSubmit={e => { e.preventDefault(); setConfirm(true) }}><h2 className="text-xl font-bold">{pending ? 'Your decision' : 'Final decision'}</h2>{pending ? <><fieldset disabled={busy} className="space-y-5"><label className="field-label" htmlFor="verification-decision">Decision<select id="verification-decision" className="form-input mt-2" value={decision} onChange={e => { setDecision(e.target.value as VerificationStatus); setConfirm(false) }}><option value="VERIFIED">Verified · Information confirmed</option><option value="FAILED">Failed · Could not verify</option><option value="FLAGGED">Flagged · Needs further review</option></select></label><Field name="verification-notes" label="Private review notes" multiline required maxLength={3000} value={notes} onChange={text => { setNotes(text); setConfirm(false) }} /><p className="text-sm text-slate-500">Notes remain private. The candidate will see the decision and review time.</p><button className="button-primary w-full" disabled={!notes.trim()}>Review decision</button></fieldset>{confirm && <div role="alert" className="rounded-xl bg-amber-50 p-4"><p className="mb-4 text-sm">Record {decision} for {v.candidateName}? This decision is final.</p><div className="flex flex-wrap gap-3"><button type="button" disabled={busy} className="button-primary" onClick={() => void submit()}>{busy ? 'Recording…' : 'Confirm decision'}</button><button type="button" disabled={busy} className="button-secondary" onClick={() => setConfirm(false)}>Cancel</button></div></div>}</> : <><p role="status" className={`rounded-xl p-4 font-semibold ${statusClass(v.status)}`}>{statusLabels[v.status]}</p><p className="whitespace-pre-wrap break-words text-sm">{v.notes}</p><p className="text-sm text-slate-500">Reviewed {v.reviewedAt && date(v.reviewedAt)}</p></>}<Link className="inline-block font-semibold text-indigo-700" to="/evaluator/verifications">← Back to verification queue</Link></form></div></>
}
