import { Link } from 'react-router'
import { useTradeText } from '../trade/useTradeText'
import { useCallback, useState, type FormEvent } from 'react'
import { useAuth } from '../auth/useAuth'
import { api, apiFailure } from '../../services/api'
import { useLoad, words } from '../marketplace/useLoad'
import { Empty, Feedback, Field, LoadState, Workspace } from '../marketplace/shared'
interface Skill { id: number; name: string; category: string; active?: boolean }
interface Program { id: number; title: string; providerName: string; description: string; active: boolean; skills: Skill[] }
interface Referral { id: number; candidate: string; program: Program; status: string; createdAt: string }
interface Candidate { candidateId: number; fullName: string; phone: string | null; candidateType: string; location: string | null; availability: string; skills: Skill[] }
const emptyProgram = { title: '', providerName: '', description: '', active: true, skillIds: [] as number[] }
const emptySearch = { name: '', phone: '', track: '', skillId: '', page: 0 }
export function TrainingPage() {
  const tr = useTradeText(), { user } = useAuth(), admin = user?.role === 'ADMIN', staff = admin || user?.role === 'EVALUATOR'
  const loader = useCallback(async () => {
    const [programs, referrals, skills] = await Promise.all([api.get<Program[]>('/training-programs'), api.get<Referral[]>('/referrals'), api.get<Skill[]>('/skills')])
    return { programs: programs.data, referrals: referrals.data, skills: skills.data }
  }, [])
  const state = useLoad(loader)
  const [candidate, setCandidate] = useState<Candidate | null>(null), [programId, setProgram] = useState('')
  const [query, setQuery] = useState(emptySearch), [search, setSearch] = useState(emptySearch)
  const candidateLoader = useCallback(async () => staff ? (await api.get<Candidate[]>('/referrals/candidates', { params: { ...search, track: search.track || undefined, skillId: search.skillId || undefined } })).data : [], [staff, search])
  const candidates = useLoad(candidateLoader)
  const [title, setTitle] = useState(''), [provider, setProvider] = useState(''), [programSkills, setProgramSkills] = useState<number[]>([])
  const [editing, setEditing] = useState<number | null>(null), [draft, setDraft] = useState(emptyProgram)
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [success, setSuccess] = useState('')
  const selectedProgram = state.data?.programs.find(p => p.id === Number(programId) && p.active)
  const programs = state.data?.programs.filter(p => p.active && p.title.toLowerCase().includes(title.toLowerCase()) && p.providerName.toLowerCase().includes(provider.toLowerCase()) && (!programSkills.length || p.skills.some(s => programSkills.includes(s.id)))) ?? []
  const toggle = (values: number[], id: number) => values.includes(id) ? values.filter(v => v !== id) : [...values, id]
  async function refer(e: FormEvent) {
    e.preventDefault(); if (!candidate || !selectedProgram) return
    setBusy(true); setError(''); setSuccess('')
    try { await api.post('/referrals', { candidateId: candidate.candidateId, programId: selectedProgram.id }); setSuccess('Referral created. The candidate has been notified.'); setCandidate(null); setProgram(''); state.reload() }
    catch (err) { setError(apiFailure(err).message) } finally { setBusy(false) }
  }
  async function save(e: FormEvent) {
    e.preventDefault(); setBusy(true); setError(''); setSuccess('')
    try {
      if (editing) await api.put(`/training-programs/${editing}`, draft); else await api.post('/training-programs', draft)
      setSuccess(editing ? 'Training program updated.' : 'Training program created.'); setEditing(null); setDraft(emptyProgram); state.reload()
    } catch (err) { setError(apiFailure(err).message) } finally { setBusy(false) }
  }
  return <Workspace title={tr('Training programs')} subtitle={tr('Explore practical learning pathways. A referral does not automatically enroll you.')}>
    <Feedback error={error} success={success} /><LoadState {...state} />
    {state.data && <div className="space-y-8">
      {!staff && <section className="surface border-indigo-200 bg-indigo-50"><h2 className="text-xl font-bold">{tr('Interested in training?')}</h2><p className="my-4 leading-relaxed">{tr('Training programs are available through referral. Book a consultation with an evaluator to discuss suitable training opportunities.')}</p><Link className="button-primary inline-flex" to="/candidate/bookings?purpose=CONSULTATION">{tr('Book consultation')}</Link></section>}
      {admin && <section className="surface"><h2 className="text-xl font-bold">Manage training programs</h2><form onSubmit={save} className="mt-5"><fieldset disabled={busy} className="grid gap-4 sm:grid-cols-2"><Field name="training-title" label="Title" required maxLength={200} value={draft.title} onChange={title => setDraft({ ...draft, title })} /><Field name="training-provider" label="Provider name" required maxLength={200} value={draft.providerName} onChange={providerName => setDraft({ ...draft, providerName })} /><div className="sm:col-span-2"><Field name="training-description" label="Description" required multiline maxLength={3000} value={draft.description} onChange={description => setDraft({ ...draft, description })} /></div><fieldset className="sm:col-span-2"><legend className="field-label">Skills · choose at least one</legend><div className="flex max-h-56 flex-wrap gap-3 overflow-auto rounded-xl border border-slate-200 p-3">{state.data.skills.map(s => <label key={s.id} className="flex items-center gap-2 p-2 text-sm"><input type="checkbox" checked={draft.skillIds.includes(s.id)} onChange={() => setDraft({ ...draft, skillIds: toggle(draft.skillIds, s.id) })} />{s.name} · {s.category}</label>)}</div>{!state.data.skills.length && <p className="mt-2 text-sm">An administrator must activate skills before creating programs.</p>}</fieldset><label className="flex items-center gap-2"><input type="checkbox" checked={draft.active} onChange={e => setDraft({ ...draft, active: e.target.checked })} />Active · visible in the catalog</label><div className="flex flex-wrap gap-3"><button className="button-primary" disabled={busy || !draft.skillIds.length}>{busy ? 'Saving…' : editing ? 'Save changes' : 'Create program'}</button>{editing && <button type="button" className="button-secondary" onClick={() => { setEditing(null); setDraft(emptyProgram) }}>Cancel edit</button>}</div></fieldset></form>
      <div className="mt-6 divide-y divide-slate-100">{state.data.programs.map(p => <div key={p.id} className="flex flex-wrap items-center justify-between gap-3 py-4"><div><p className="font-semibold">{p.title} · {p.active ? 'Active' : 'Inactive'}</p><p className="text-sm text-slate-500">{p.providerName} · {p.skills.map(s => s.name).join(', ') || 'Choose skills when editing'}</p></div><button className="button-secondary" disabled={busy} onClick={() => { setEditing(p.id); setDraft({ title: p.title, providerName: p.providerName, description: p.description ?? '', active: p.active, skillIds: p.skills.filter(s => state.data?.skills.some(active => active.id === s.id)).map(s => s.id) }); document.getElementById('training-title')?.focus() }}>Edit program</button></div>)}</div></section>}
      {staff && <section className="surface space-y-5"><h2 className="text-xl font-bold">Refer a candidate</h2><p className="text-sm text-slate-600">Search active candidates, then choose a program. An assessment result is not required.</p>
        <form onSubmit={e => { e.preventDefault(); setSearch({ ...query, page: 0 }) }} className="grid gap-3 sm:grid-cols-2"><Field name="candidate-name" label="Candidate name" value={query.name} onChange={name => setQuery({ ...query, name })} /><Field name="candidate-phone" label="Phone" value={query.phone} onChange={phone => setQuery({ ...query, phone })} /><div><label htmlFor="candidate-track" className="field-label">Track</label><select id="candidate-track" className="form-input" value={query.track} onChange={e => setQuery({ ...query, track: e.target.value })}><option value="">All tracks</option><option>TECH</option><option>TRADE</option></select></div><div><label htmlFor="candidate-skill" className="field-label">Candidate skill</label><select id="candidate-skill" className="form-input" value={query.skillId} onChange={e => setQuery({ ...query, skillId: e.target.value })}><option value="">All skills</option>{state.data.skills.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></div><button className="button-secondary" disabled={candidates.loading}>Search candidates</button></form>
        <LoadState {...candidates} />{!candidates.loading && !candidates.error && candidates.data && <><div className="grid max-h-96 gap-3 overflow-auto sm:grid-cols-2">{candidates.data.map(c => <button type="button" key={c.candidateId} aria-pressed={candidate?.candidateId === c.candidateId} className={`rounded-xl border p-4 text-left ${candidate?.candidateId === c.candidateId ? 'border-indigo-500 bg-indigo-50' : 'border-slate-200'}`} onClick={() => setCandidate(c)}><span className="block font-semibold">{c.fullName}</span><span className="mt-1 block text-sm">{c.phone || 'No phone'} · {c.candidateType} · {words(c.availability)}</span><span className="mt-1 block text-sm text-slate-500">{c.location}{c.location && ' · '}{c.skills.map(s => s.name).join(', ') || 'No skills listed'}</span></button>)}</div>{!candidates.data.length && <p>No candidates match these filters.</p>}<div className="flex items-center gap-3"><button className="button-secondary" disabled={!search.page} onClick={() => setSearch({ ...search, page: search.page - 1 })}>Previous</button><span className="text-sm">Page {search.page + 1}</span><button className="button-secondary" disabled={candidates.data.length < 20} onClick={() => setSearch({ ...search, page: search.page + 1 })}>Next</button></div></>}
        <div className="grid gap-3 sm:grid-cols-2"><Field name="program-search-title" label="Program title" value={title} onChange={value => { setTitle(value); setProgram('') }} /><Field name="program-search-provider" label="Provider" value={provider} onChange={value => { setProvider(value); setProgram('') }} /></div><fieldset><legend className="field-label">Program skills · any selected skill</legend><div className="flex max-h-40 flex-wrap gap-3 overflow-auto">{state.data.skills.map(s => <label key={s.id} className="flex items-center gap-2 p-2 text-sm"><input type="checkbox" checked={programSkills.includes(s.id)} onChange={() => { setProgramSkills(toggle(programSkills, s.id)); setProgram('') }} />{s.name}</label>)}</div></fieldset>
        <form onSubmit={refer} className="space-y-4"><label htmlFor="referral-program" className="field-label">Active training program</label><select id="referral-program" required className="form-input" value={programId} onChange={e => setProgram(e.target.value)}><option value="">Choose a program</option>{programs.map(p => <option key={p.id} value={p.id}>{p.title} · {p.providerName}{candidate && p.skills.some(s => candidate.skills.some(cs => cs.id === s.id)) ? ' · Skill match' : ''}</option>)}</select>{!programs.length && <p className="text-sm">No active programs match these filters.</p>}
        <div className="rounded-xl bg-slate-50 p-4 text-sm"><p><strong>Candidate:</strong> {candidate ? `${candidate.fullName} · ${candidate.phone || candidate.candidateType}` : 'Select a candidate above'}</p><p className="mt-2"><strong>Program:</strong> {selectedProgram ? `${selectedProgram.title} · ${selectedProgram.providerName}` : 'Select a program above'}</p>{selectedProgram && <p className="mt-2">Skills: {selectedProgram.skills.map(s => s.name).join(', ') || 'General training'}</p>}{candidate && selectedProgram && <p className="mt-2">{selectedProgram.skills.some(s => candidate.skills.some(cs => cs.id === s.id)) ? 'Matches an existing candidate skill.' : 'No existing skill overlap. Training can develop a new skill.'}</p>}</div><button disabled={busy || !candidate || !selectedProgram} className="button-primary">{busy ? 'Sending referral…' : 'Confirm referral & notify candidate'}</button></form>
      </section>}
      <section><h2 className="mb-4 text-xl font-bold">{staff ? 'Referral activity' : tr('My referrals')}</h2><div className="grid gap-4 sm:grid-cols-2">{state.data.referrals.map(r => <article key={r.id} className="surface"><span className="badge">{tr(words(r.status))}</span><h3 className="mt-4 text-lg font-bold">{r.program.title}</h3><p className="mt-2 text-sm text-slate-600">{staff ? `${r.candidate} · ` : ''}{r.program.providerName}</p><p className="mt-3 whitespace-pre-wrap break-words text-slate-600">{r.program.description}</p><p className="mt-4 text-sm text-slate-500">{tr('Referred')} {new Date(r.createdAt).toLocaleDateString()}</p></article>)}</div>{!state.data.referrals.length && <Empty title={tr('No referrals yet')}>{tr('An evaluator or administrator can refer a candidate to an active program.')}</Empty>}</section>
      <section><h2 className="mb-4 text-xl font-bold">{tr('Learning catalog')}</h2><div className="grid gap-4 sm:grid-cols-2">{state.data.programs.filter(p => p.active).map(p => <article key={p.id} className="surface"><p className="eyebrow">{p.skills.map(s => s.name).join(' · ') || tr('FOUNDATION SKILLS')}</p><h3 className="mt-3 text-xl font-bold">{p.title}</h3><p className="mt-2 text-sm font-medium text-indigo-700">{p.providerName}</p><p className="mt-4 whitespace-pre-wrap break-words leading-relaxed text-slate-600">{p.description}</p></article>)}</div>{!state.data.programs.some(p => p.active) && <Empty title={tr('New programs are on the way')}>{tr('Check back with your evaluator for learning options.')}</Empty>}</section>
    </div>}
  </Workspace>
}
