import { useCallback, useState, type FormEvent } from 'react'
import { api, apiFailure } from '../../services/api'
import { Modal } from '../../components/Modal'
import { Empty, Feedback, LoadState } from '../marketplace/shared'
import { useLoad, words } from '../marketplace/useLoad'
import { CompanyTypeSelector } from '../company-types/CompanyTypeSelector'

type Value = string | number | boolean | null
interface Row { id: number; title: string; subtitle: string; status: string; fields: Record<string, Value> }
interface Page { content: Row[]; totalElements: number; page: number; totalPages: number }
interface FieldSpec { key: string; label: string; max?: number; required?: boolean; type?: 'number' | 'textarea' | 'checkbox'; options?: string[] }
const text = (key: string, label: string, max: number, required = false): FieldSpec => ({ key, label, max, required })
const forms: Record<string, FieldSpec[]> = {
  candidates: [text('fullName', 'Full name', 160, true), text('phone', 'Phone', 32), text('location', 'Location', 255), { key: 'bio', label: 'Profile summary', type: 'textarea', max: 2000 }, text('educationSummary', 'Education', 2000), text('experienceSummary', 'Experience summary', 2000), { key: 'totalExperienceMonths', label: 'Experience in months', type: 'number', required: true }, { key: 'availability', label: 'Availability', options: ['AVAILABLE', 'UNAVAILABLE'], required: true }, text('primaryTradeCategory', 'Trade category', 120), text('portfolioUrl', 'Portfolio URL', 2048)],
  employers: [text('companyName', 'Company name', 200, true), text('contactPhone', 'Contact phone', 32), text('address', 'Address', 500), { key: 'description', label: 'Company description', type: 'textarea', max: 2000 }],
  jobs: [text('title', 'Job title', 200, true), { key: 'description', label: 'Description', type: 'textarea', max: 5000, required: true }, text('location', 'Location', 255, true), { key: 'candidateType', label: 'Candidate track', options: ['TECH', 'TRADE'], required: true }, { key: 'requiredSkillId', label: 'Required skill ID (optional; see Skills)', type: 'number' }, { key: 'expectedExperienceMonths', label: 'Expected experience in months', type: 'number', required: true }, { key: 'publicExpectations', label: 'Public expectations', type: 'textarea', max: 5000 }, { key: 'privateExpectations', label: 'Private employer expectations', type: 'textarea', max: 5000 }],
  skills: [text('name', 'Skill name', 120, true), text('category', 'Category', 120, true), { key: 'active', label: 'Active', type: 'checkbox' }],
}
const statuses: Record<string, string[]> = {
  users: ['ACTIVE', 'SUSPENDED', 'FLAGGED', 'BLOCKED'], candidates: ['ACTIVE', 'SUSPENDED', 'FLAGGED', 'BLOCKED'], employers: ['ACTIVE', 'SUSPENDED', 'FLAGGED', 'BLOCKED'], jobs: ['DRAFT', 'ACTIVE', 'CLOSED'], applications: ['APPLIED', 'UNDER_REVIEW', 'SHORTLISTED', 'REJECTED', 'WITHDRAWN'], bookings: ['PENDING_PAYMENT', 'BOOKED', 'CANCELLED', 'COMPLETED'], payments: ['PENDING', 'SUCCESS', 'CANCELLED'], assessments: ['NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'FAILED'], attempts: ['IN_PROGRESS', 'SUBMITTED', 'EVALUATED'], skills: ['true', 'false'],
}
const label = (key: string) => key.replace(/([A-Z])/g, ' $1').replace(/^./, c => c.toUpperCase())
export function AdminRecords({ section, changed }: { section: string; changed: () => void }) {
  const [page, setPage] = useState(0), [search, setSearch] = useState(''), [draftSearch, setDraftSearch] = useState(''), [status, setStatus] = useState('')
  const loader = useCallback(() => api.get<Page>(`/admin/records/${section}`, { params: { page, size: 12, search, status } }).then(r => r.data), [section, page, search, status])
  const state = useLoad(loader)
  const [selected, setSelected] = useState<Row | null>(null), [editing, setEditing] = useState(false), [form, setForm] = useState<Record<string, Value>>({})
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [success, setSuccess] = useState('')
  const [pending, setPending] = useState<{ title: string; message: string; path: string; body?: object; method: 'post' | 'patch' | 'put' } | null>(null)
  function refresh() { state.reload(); changed() }
  function open(row: Row, edit = false) { setSelected(row); setEditing(edit); setForm({ ...row.fields }); setError('') }
  function create() { open({ id: 0, title: section === 'jobs' ? 'New job draft' : 'New skill', subtitle: '', status: 'DRAFT', fields: section === 'jobs' ? { candidateType: 'TECH', expectedExperienceMonths: 0 } : { active: true } }, true) }
  async function perform(path: string, body: object | undefined, method: 'post' | 'patch' | 'put') {
    setBusy(true); setError(''); setSuccess('')
    try { await api[method](path, body); setPending(null); setSelected(null); setSuccess('Changes saved.'); refresh() } catch (e) { setError(apiFailure(e).message) } finally { setBusy(false) }
  }
  function save(e: FormEvent) {
    e.preventDefault(); if (!selected) return
    const body: Record<string, Value> = {}
    for (const field of forms[section] ?? []) body[field.key] = form[field.key] ?? (field.type === 'number' ? null : field.type === 'checkbox' ? false : '')
    if (section === 'employers') { body.companyTypeId = form.companyTypeId ?? null; body.customCompanyType = form.customCompanyType ?? '' }
    const path = `/admin/${section}${selected.id ? `/${selected.id}` : ''}`, method = selected.id ? 'put' : 'post'
    if (section === 'skills' && selected.id && selected.fields.active && !body.active) { setPending({ title: 'Deactivate skill', message: 'Existing history will remain. This skill will no longer be selectable.', path, body, method }); return }
    void perform(path, section === 'jobs' && !selected.id ? { employerId: form.employerId, job: body } : body, method)
  }
  function accountStatus(row: Row, next: string) { setPending({ title: 'Change account status', message: `Set ${row.title} to ${words(next)}? Inactive accounts lose access immediately. History is preserved.`, path: `/admin/users/${section === 'users' ? row.id : row.fields.userId}/status`, body: { status: next }, method: 'patch' }) }
  return <section className="surface space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-bold capitalize">{section === 'attempts' ? 'Skills assessment attempts' : section === 'payments' ? 'Demo payments' : section}</h2><div className="flex gap-2">{['jobs', 'skills'].includes(section) && <button className="button-primary" onClick={create}>Add {section === 'jobs' ? 'job draft' : 'skill'}</button>}<button className="button-secondary" onClick={state.reload}>Refresh</button></div></div>
    {section === 'payments' && <p className="rounded-xl bg-amber-50 p-4 text-amber-900">Demo transactions only. No real money moves. Amounts, payer and resource links are read-only.</p>}
    {section === 'jobs' && <p className="text-sm text-slate-600">New drafts use the existing employer demo-payment workflow. Closing a job preserves applications and payment history.</p>}
    {['assessments', 'attempts', 'applications'].includes(section) && <p className="text-sm text-slate-600">Evaluation results are read-only. Provider instructions and private transcripts are excluded.</p>}
    <Feedback error={!selected && !pending ? error : ''} success={success} />
    <form className="flex flex-wrap items-end gap-3" onSubmit={e => { e.preventDefault(); setSearch(draftSearch); setPage(0) }}><label className="min-w-0 w-full sm:w-auto sm:flex-1"><span className="field-label">Search {section}{section === 'users' ? ' by email or role' : section === 'payments' ? ' by reference, payer or purpose' : ''}</span><input className="form-input" type="search" maxLength={200} value={draftSearch} onChange={e => setDraftSearch(e.target.value)} /></label><label><span className="field-label">Status</span><select className="form-input" value={status} onChange={e => { setStatus(e.target.value); setPage(0) }}><option value="">All statuses</option>{statuses[section]?.map(s => <option key={s} value={s}>{section === 'skills' ? s === 'true' ? 'Active' : 'Inactive' : words(s)}</option>)}</select></label><button className="button-secondary">Search</button></form>
    <LoadState {...state} />
    <div className="divide-y divide-slate-100">{state.data?.content.map(row => <article className="flex flex-wrap items-center justify-between gap-4 py-5" key={row.id}><div className="min-w-0"><h3 className="font-bold">{row.title}</h3><p className="mt-1 text-sm text-slate-600">#{row.id} · {row.subtitle}</p><span className="badge mt-2">{words(row.status)}</span></div><div className="flex flex-wrap gap-2"><button className="button-secondary" onClick={() => open(row)}>Details<span className="sr-only"> {row.title}</span></button>{forms[section] && (section !== 'jobs' || row.status !== 'CLOSED') && <button className="button-secondary" onClick={() => open(row, true)}>Edit<span className="sr-only"> {row.title}</span></button>}
      {section === 'jobs' && <button className="button-secondary" onClick={() => setPending({ title: row.status === 'CLOSED' ? 'Activate job' : 'Close job', message: row.status === 'CLOSED' ? 'Reopen this job for applications? A successful demo posting payment and active employer are required.' : 'Stop applications and cancel any pending demo posting payment? All existing history will remain.', path: `/admin/jobs/${row.id}/${row.status === 'CLOSED' ? 'activate' : 'close'}`, method: 'post' })}>{row.status === 'CLOSED' ? 'Activate' : 'Close'}</button>}
      {section === 'bookings' && ['PENDING_PAYMENT', 'BOOKED'].includes(row.status) && <button className="button-secondary" onClick={() => setPending({ title: 'Cancel booking', message: 'Cancel this eligible booking and its pending demo payment? Successful transactions remain unchanged.', path: `/admin/bookings/${row.id}/cancel`, method: 'post' })}>Cancel booking</button>}
      {['users', 'candidates', 'employers'].includes(section) && row.subtitle !== 'ADMIN' && <label><span className="sr-only">Account status for {row.title}</span><select className="form-input" value={row.status} onChange={e => accountStatus(row, e.target.value)}>{statuses.users.map(s => <option key={s} value={s}>{words(s)}</option>)}</select></label>}
      {section === 'applications' && row.status !== 'WITHDRAWN' && <label><span className="sr-only">Application status for {row.title}</span><select className="form-input" value={row.status} onChange={e => setPending({ title: 'Change application status', message: `Set this application to ${words(e.target.value)}? Eligibility and shortlist rules still apply.`, path: `/admin/applications/${row.id}/status`, body: { status: e.target.value }, method: 'patch' })}>{statuses.applications.filter(s => s !== 'WITHDRAWN').map(s => <option key={s} value={s}>{words(s)}</option>)}</select></label>}
    </div></article>)}</div>
    {state.data && !state.data.content.length && <Empty title="No matching records">Try a different search or status.</Empty>}
    {state.data && <div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-slate-600">{state.data.totalElements} records · Page {page + 1} of {Math.max(1, state.data.totalPages)}</p><div className="flex gap-2"><button className="button-secondary" disabled={!page} onClick={() => setPage(p => p - 1)}>Previous</button><button className="button-secondary" disabled={page + 1 >= state.data.totalPages} onClick={() => setPage(p => p + 1)}>Next</button></div></div>}
    {selected && !pending && <Modal title={editing ? selected.id ? `Edit ${selected.title}` : selected.title : selected.title} close={() => { if (!busy) setSelected(null) }}><div className="max-h-[70vh] overflow-y-auto px-1"><Feedback error={error} />{editing ? <form onSubmit={save}><fieldset disabled={busy} className="space-y-4">
      {section === 'jobs' && !selected.id && <label className="block"><span className="field-label">Employer profile ID (from Employers)</span><input className="form-input" type="number" min="1" step="1" required value={String(form.employerId ?? '')} onChange={e => setForm({ ...form, employerId: Number(e.target.value) })} /></label>}
      {forms[section]?.filter(f => section !== 'candidates' || (selected.fields.candidateType === 'TRADE' ? !['educationSummary', 'portfolioUrl'].includes(f.key) : f.key !== 'primaryTradeCategory')).map(f => <label className="block" key={f.key}><span className="field-label">{f.label}</span>{f.options ? <select className="form-input" required={f.required} value={String(form[f.key] ?? '')} onChange={e => setForm({ ...form, [f.key]: e.target.value })}><option value="">Select…</option>{f.options.map(v => <option key={v} value={v}>{words(v)}</option>)}</select> : f.type === 'checkbox' ? <input type="checkbox" checked={!!form[f.key]} onChange={e => setForm({ ...form, [f.key]: e.target.checked })} /> : f.type === 'textarea' ? <textarea className="form-input" rows={4} required={f.required} maxLength={f.max} value={String(form[f.key] ?? '')} onChange={e => setForm({ ...form, [f.key]: e.target.value })} /> : <input className="form-input" type={f.type ?? 'text'} min={f.key === 'requiredSkillId' ? 1 : 0} step={f.type === 'number' ? 1 : undefined} required={f.required} maxLength={f.max} value={String(form[f.key] ?? '')} onChange={e => setForm({ ...form, [f.key]: f.type === 'number' ? e.target.value === '' ? null : Number(e.target.value) : e.target.value })} />}</label>)}
      {section === 'employers' && <CompanyTypeSelector value={Number(form.companyTypeId) || null} custom={String(form.customCompanyType ?? '')} selected={selected.fields.companyTypeId ? { id: Number(selected.fields.companyTypeId), name: String(selected.fields.companyTypeName), active: !!selected.fields.companyTypeActive, other: !!selected.fields.companyTypeOther } : undefined} onChange={(type, custom) => setForm({ ...form, companyTypeId: type?.id ?? null, customCompanyType: custom })} />}
      <div className="flex gap-3"><button className="button-primary">{busy ? 'Saving…' : 'Save'}</button><button type="button" className="button-secondary" onClick={() => setSelected(null)}>Cancel</button></div>
    </fieldset></form> : <><p className="mb-4 text-sm text-slate-600">{selected.subtitle} · {words(selected.status)}</p><dl className="space-y-4">{Object.entries(selected.fields).map(([key, value]) => <div key={key}><dt className="text-sm font-semibold text-slate-500">{label(key)}</dt><dd className="mt-1 whitespace-pre-wrap break-words">{value == null || value === '' ? '—' : String(value)}</dd></div>)}</dl><button className="button-secondary mt-6" onClick={() => setSelected(null)}>Close</button></>}</div></Modal>}
    {pending && <Modal title={pending.title} close={() => { if (!busy) setPending(null) }}><Feedback error={error} /><p>{pending.message}</p><div className="mt-5 flex gap-3"><button className="button-primary" disabled={busy} onClick={() => void perform(pending.path, pending.body, pending.method)}>{busy ? 'Saving…' : 'Confirm'}</button><button className="button-secondary" disabled={busy} onClick={() => setPending(null)}>Go back</button></div></Modal>}
  </section>
}
