import { useCallback, useState, type FormEvent } from 'react'
import { api, apiFailure } from '../../services/api'
import { useLoad, words } from '../marketplace/useLoad'
import { Modal } from '../../components/Modal'
import { Field, Feedback, LoadState, Empty } from '../marketplace/shared'
import { documentLabel, downloadDocument, type Review } from './api'
const loadTypes = () => api.get<{ id: number; name: string }[]>('/admin/company-types').then(r => r.data)
export function VerificationReviews() {
  const [status, setStatus] = useState('PENDING'), [role, setRole] = useState(''), [company, setCompany] = useState('')
  const [page, setPage] = useState(0)
  const loader = useCallback(() => api.get<{ content: Review[]; totalElements: number; totalPages: number }>('/admin/verification-submissions/page', { params: { status, role, companyId: company || undefined, page, size: 12 } }).then(r => r.data), [status, role, company, page])
  const state = useLoad(loader)
  const typesState = useLoad(loadTypes)
  const [selected, setSelected] = useState<Review | null>(null), [decision, setDecision] = useState('VERIFIED'), [notes, setNotes] = useState('')
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [success, setSuccess] = useState('')
  async function download(id: number) { setError(''); try { await downloadDocument(id) } catch (e) { setError(apiFailure(e).message) } }
  async function review(e: FormEvent) {
    e.preventDefault(); if (!selected) return; setBusy(true); setError(''); setSuccess('')
    try { await api.post(`/admin/verification-submissions/${selected.id}/review`, { status: decision, notes }); setSelected(null); setSuccess('Review recorded.'); state.reload() }
    catch (e) { setError(apiFailure(e).message) } finally { setBusy(false) }
  }
  const rows = state.data?.content ?? []
  const types = typesState.data ?? []
  return <section className="surface space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-bold">Verification reviews</h2><button className="button-secondary" onClick={state.reload}>Refresh</button></div><Feedback error={error} success={success} />
    <div className="grid gap-3 sm:grid-cols-3"><div><label className="field-label" htmlFor="review-status">Status</label><select className="form-input" id="review-status" value={status} onChange={e => { setStatus(e.target.value); setPage(0) }}><option value="PENDING">Pending review</option><option value="VERIFIED">Approved</option><option value="FAILED">Rejected</option><option value="">All, including history</option></select></div><div><label className="field-label" htmlFor="review-role">Account type</label><select id="review-role" className="form-input" value={role} onChange={e => { setRole(e.target.value); setPage(0) }}><option value="">All accounts</option><option value="CANDIDATE">Candidates</option><option value="EMPLOYER">Employers</option></select></div><div><label className="field-label" htmlFor="review-company">Company type</label><select id="review-company" className="form-input" value={company} onChange={e => { setCompany(e.target.value); setPage(0) }}><option value="">All company types</option>{types.map(({id, name}) => <option key={id} value={id!}>{name}</option>)}</select></div></div>
    {typesState.error && <Feedback error={typesState.error} />}<LoadState {...state} /><div className="divide-y divide-slate-100">{rows.map(r => <article key={r.id} className="flex flex-wrap items-center justify-between gap-4 py-5"><div className="min-w-0"><h3 className="font-bold break-words">{r.ownerName} · {r.requirementName}</h3><p className="mt-2 text-sm text-slate-600">{words(r.role)}{r.companyTypeName && ` · ${r.companyTypeName}`} · {documentLabel(r.status)}</p><p className="mt-1 text-xs text-slate-500">{new Date(r.submittedAt).toLocaleString()}{!r.latest ? ' · Replaced' : !r.applicable ? ' · No longer applicable' : ''}</p>{r.reviewNote && <p className="mt-2 whitespace-pre-wrap break-words text-sm">{r.reviewNote}</p>}{r.reviewedAt && <p className="mt-1 text-xs text-slate-500">Reviewed {new Date(r.reviewedAt).toLocaleString()}</p>}</div><div className="flex flex-wrap gap-2">{r.hasFile && <button className="button-secondary" onClick={() => void download(r.id)}>Download<span className="sr-only"> submission {r.id}</span></button>}<button className="button-secondary" onClick={() => { setSelected(r); setNotes(''); setDecision('VERIFIED'); setError('') }}>{r.latest && r.applicable && ['PENDING', 'IN_REVIEW'].includes(r.status) ? 'Review' : 'Details'}<span className="sr-only"> submission {r.id}</span></button></div></article>)}</div>
    {!state.loading && !state.error && !rows.length && <Empty title="No matching submissions">Try another filter or refresh when new documents arrive.</Empty>}
    {state.data && <div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-slate-600">{state.data.totalElements} submissions · Page {page + 1} of {Math.max(1, state.data.totalPages)}</p><div className="flex gap-2"><button className="button-secondary" disabled={!page} onClick={() => setPage(p => p - 1)}>Previous</button><button className="button-secondary" disabled={page + 1 >= state.data.totalPages} onClick={() => setPage(p => p + 1)}>Next</button></div></div>}
    {selected && <Modal title={`${selected.ownerName} · ${selected.requirementName}`} close={() => { if (!busy) setSelected(null) }}><Feedback error={error} /><p className="my-4 text-sm">{documentLabel(selected.status)} · {words(selected.role)}. Review is limited to verification evidence.</p>{selected.hasFile ? <button className="button-secondary mb-4" onClick={() => void download(selected.id)}>Download private document</button> : <p className="mb-4 whitespace-pre-wrap break-words rounded-xl bg-slate-50 p-4">Legacy identity reference: {selected.identityReference ?? 'Not recorded'}</p>}{selected.latest && selected.applicable && ['PENDING', 'IN_REVIEW'].includes(selected.status) ? <form onSubmit={review}><fieldset disabled={busy} className="space-y-4"><div><label className="field-label" htmlFor="document-decision">Decision</label><select id="document-decision" className="form-input" value={decision} onChange={e => setDecision(e.target.value)}><option value="VERIFIED">Approve</option><option value="FAILED">Reject</option></select></div><Field name="document-notes" label={selected.hasFile ? 'Feedback for the document owner' : 'Private legacy review notes'} value={notes} onChange={setNotes} maxLength={3000} multiline required={decision === 'FAILED'} /><button className="button-primary" disabled={busy}>{busy ? 'Recording…' : 'Record decision'}</button></fieldset></form> : <p className="whitespace-pre-wrap break-words">{selected.reviewNote || 'This submission is historical or has a final decision.'}</p>}</Modal>}
  </section>
}
