import { Link } from 'react-router'

export function HomePage() {
  return <div className="space-y-16 sm:space-y-24">
    <section className="grid items-center gap-10 lg:grid-cols-[1.25fr_1fr]">
      <div><p className="eyebrow text-indigo-700">BUILT FOR BANGLADESH · OPEN TO POSSIBILITY</p><h1 className="mt-5 text-4xl font-bold leading-tight tracking-tight sm:text-6xl">Real skills.<br />Recognized.<br /><span className="text-indigo-600">Ready for what’s next.</span></h1><p className="mt-6 max-w-xl text-lg leading-relaxed text-slate-600">A clearer path to work for professionals and field workers. Show your skills, get a human review and connect with employers who value your potential.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/register" className="button-primary">Find my next opportunity →</Link><Link to="/register?account=employer" className="button-secondary">I’m hiring</Link></div><p className="mt-4 text-sm text-slate-500">Two candidate tracks. One platform built around trust.</p></div>
      <aside className="relative overflow-hidden rounded-3xl bg-slate-900 p-7 text-white sm:p-9"><div className="flex items-center justify-between gap-3"><p className="text-sm font-semibold text-emerald-300">A path you can follow</p><span className="rounded-full border border-slate-600 px-3 py-1 text-xs">Illustrative journey</span></div><h2 className="mt-7 text-2xl font-bold">Your skills tell a story.<br />Let’s make it visible.</h2><ol className="mt-8 space-y-5">{[['01', 'Build your profile', 'TECH portfolios or Bangla-assisted TRADE onboarding.'], ['02', 'Show what you know', 'Assessments and a practical evaluator review.'], ['03', 'Move forward with confidence', 'Hiring opportunities or a recommended learning path.']].map(([n, title, text]) => <li key={n} className="flex gap-4"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-slate-800 font-bold text-emerald-300">{n}</span><div><h3 className="font-semibold">{title}</h3><p className="mt-1 text-sm leading-relaxed text-slate-300">{text}</p></div></li>)}</ol><div className="mt-8 rounded-xl bg-emerald-400/10 p-4 text-sm text-emerald-200">Human-reviewed skills. Clear status. A next step for every candidate.</div></aside>
    </section>
    <section aria-labelledby="tracks-title"><p className="eyebrow">DIFFERENT STRENGTHS. EQUAL POSSIBILITY.</p><h2 id="tracks-title" className="mt-3 text-3xl font-bold tracking-tight">Choose the path that feels like you.</h2><div className="mt-7 grid gap-5 sm:grid-cols-2"><article className="surface"><span className="badge bg-indigo-50 text-indigo-800">TECH · Professional careers</span><h3 className="mt-5 text-2xl font-bold">From knowledge to opportunity.</h3><p className="mt-4 leading-relaxed text-slate-600">For students, developers, engineers and designers. Bring your profile, skills and CV together, take an assessment and receive feedback from an evaluator.</p><Link to="/register" className="mt-6 inline-flex min-h-11 items-center font-semibold text-indigo-700">Build my professional profile →</Link></article><article className="surface border-emerald-200 bg-emerald-50/40"><span className="badge bg-emerald-100 text-emerald-800">TRADE · Practical expertise</span><h3 lang="bn" className="mt-5 text-2xl font-bold">আপনার দক্ষতাই আপনার পরিচয়।</h3><p className="mt-4 leading-relaxed text-slate-600">For drivers, electricians, mechanics and field workers. Get started in Bangla, use optional voice input and build a verified path into the managed workforce.</p><Link to="/register?track=TRADE" className="mt-6 inline-flex min-h-11 items-center font-semibold text-emerald-800">শুরু করুন · Get started →</Link></article></div></section>
    <section className="grid gap-8 rounded-3xl border border-slate-200 bg-white p-7 sm:p-10 lg:grid-cols-2"><div><p className="eyebrow text-emerald-700">ACCESS STARTS WITH UNDERSTANDING</p><h2 className="mt-3 text-3xl font-bold">Speak in Bangla.<br />Move at your own pace.</h2><p className="mt-4 leading-relaxed text-slate-600">Optional voice input helps you fill your profile. Review and edit the transcript before applying it. Typing is always available, even when your browser cannot support speech.</p></div><div lang="bn" className="rounded-2xl bg-stone-50 p-6"><p className="text-sm font-semibold text-emerald-800">১ · কাজ বাছুন → ২ · পরিচয় দিন → ৩ · দেখে সংরক্ষণ করুন</p><p className="mt-5 text-2xl font-semibold">সহজ ভাষায়, নিজের কথা বলুন।</p><p className="mt-4 leading-relaxed text-slate-600">মাইক্রোফোন ব্যবহার করুন অথবা লিখুন। সংরক্ষণের আগে সব তথ্য নিজে দেখে নিন।</p></div></section>
    <section><p className="eyebrow">TRUST IS A PROCESS</p><h2 className="mt-3 text-3xl font-bold">Clear checks. People behind every decision.</h2><div className="mt-7 grid gap-5 md:grid-cols-3">{[['Profile & evidence', 'Candidates submit their information for platform/manual verification. This is not government NID integration.'], ['Skills & feedback', 'Evaluators review assessments and release a readiness result, with a training referral when more practice would help.'], ['Ready for managed work', 'Eligible, available TRADE candidates join a skill-based waiting list. Eligibility is checked again before selection.']].map(([title, body], i) => <article key={title} className="surface"><p className="eyebrow text-indigo-700">0{i + 1}</p><h3 className="mt-4 text-xl font-bold">{title}</h3><p className="mt-3 leading-relaxed text-slate-600">{body}</p></article>)}</div></section>
    <section className="rounded-3xl bg-slate-900 p-7 text-white sm:p-10"><p className="eyebrow text-emerald-300">FOR EMPLOYERS · KEEP WORK MOVING</p><h2 className="mt-3 text-3xl font-bold">A managed replacement.<br />A visible 24-hour target.</h2><p className="mt-5 max-w-2xl leading-relaxed text-slate-300">For eligible TRADE placements within coverage, request a replacement and follow every step. The platform checks the waiting list in FIFO order, reserves an eligible worker and tracks the SLA through activation.</p><ol className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{['Request received', 'Eligible worker selected', 'Employer confirms', 'Replacement activated'].map((s, i) => <li key={s} className="rounded-xl border border-slate-700 p-5"><span className="text-sm font-semibold text-emerald-300">0{i + 1}</span><p className="mt-3 font-semibold">{s}</p></li>)}</ol><p className="mt-5 text-sm text-slate-300">Availability matters: an empty eligible queue is shown clearly. The 24-hour target is tracked, not a promise of an available worker.</p><Link to="/register?account=employer" className="button-primary mt-7">Build my hiring team →</Link></section>
    <section className="text-center"><p className="eyebrow">YOUR NEXT CHAPTER</p><h2 className="mt-4 text-3xl font-bold">Good work starts with a chance.</h2><p className="mx-auto mt-4 max-w-xl leading-relaxed text-slate-600">Create your candidate or employer account and take the first step.</p><Link to="/register" className="button-primary mt-6">Join Verified Career</Link><p className="mt-5 text-sm text-slate-500">University showcase · Demo people and providers are fictional.</p></section>
  </div>
}
